/****************************************************************************/
//    Copyright (C) 2026 HobbitDur                                          //
//                                                                          //
//    This file is part of FFNx                                             //
//                                                                          //
//    FFNx is free software: you can redistribute it and/or modify          //
//    it under the terms of the GNU General Public License as published by  //
//    the Free Software Foundation, either version 3 of the License         //
//                                                                          //
//    FFNx is distributed in the hope that it will be useful,               //
//    but WITHOUT ANY WARRANTY; without even the implied warranty of        //
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         //
//    GNU General Public License for more details.                          //
/****************************************************************************/

// Effect 203: Cerberus (cinematic-engine GF, module 0xB0C180..0xB18980, script data
// magic/MAG202_B.00/.01, streamed parts battle/mag202_b.02..). One clone of the GF cinematic
// engine (gfc_engine.cpp); this file holds the clone descriptor and the ports of the handlers that
// are not byte clones of the generic (Ifrit) ones.

#include "gfc_engine.h"

#ifdef FF8_FX_HELD
#include "mag_cerberus_held.h"
#endif

// ==== BEGIN clone handler parts (generated by integrate.py) ====
// ---- part cerberus
namespace ff8fx
{
namespace gfc
{
namespace part_cerberus
{
	// ------------------------------------------------------------------------------------
	// local wrappers
	// ------------------------------------------------------------------------------------
	// 0xB65150 xorEAX_6: `xor eax, eax; ret` (called by 0xB11D5D, result unused). No effect; called at its address for call-trace parity.
	static inline void xl_Nop_B65150() { blob::f<int32_t (__cdecl *)()>(0xB65150)(); }

	// fild qword [u16 zero-extended DEPTHARR[off >> 3]]; fmul dword [0x1877DA8]; call __ftol
	// (u16 x float = at most 40 significant bits: exact in a double; __ftol truncates to int64,
	// the callers keep the low dword)
	static inline int32_t DepthKey(uint32_t off)
	{
		uint32_t v = DEPTHARR()[off >> 3] & 0xFFFF;
		return (int32_t)(int64_t)((double)v * (double)FLT_1877DA8());
	}

	// mov [t], 0x55555556; imul dword [t] (edx:eax = v * 0x55555556); sar v, 0x1F; edx - that
	static inline int32_t Div3(int32_t v)
	{
		int32_t hi = (int32_t)(((int64_t)v * (int64_t)0x55555556) >> 32);
		return sub32(hi, v >> 31);
	}

	// NCLIP of three screen vertices (GTE SXY0..2 = data regs 12..14), MAC0 (data reg 24)
	static inline int32_t Nclip(uint32_t s0, uint32_t s1, uint32_t s2)
	{
		int32_t mac0;
		x::GteWriteData((int32_t)s0, 12);
		x::GteWriteData((int32_t)s1, 13);
		x::GteWriteData((int32_t)s2, 14);
		x::GteNCLIP();
		x::GteReadData(&mac0, 24);
		return mac0;
	}

	// ------------------------------------------------------------------------------------
	// 0xB11C30 (Draw 45 ScreenMelt): the screen (a 320x224 copy in VRAM) falls apart in 320
	// one-pixel columns.
	// bone+0xB8 -> parameter block (u16):
	//   +0 VRAM x, +2 VRAM y of the copy (-> tpage bone+0xC0, first call),
	//   +4 initial speed base, +6 its per-column step, +8 sine phase, +0xA its per-column step,
	//   +0xC random speed range (Rand73), +0xE acceleration base, +0x10 random acceleration
	//   range (Rand73), +0x12 speed offset, +0x14 fall limit (<< 8).
	// bone+0xBC -> block 0x2810 (arena, first call): +0 s16 tick counter (red fade, 0..15 used),
	//   +0x10 320 columns x 0x20: +0 u16 flags (bit0 = bottom passed the limit: draw the cap line,
	//   bit15 = gone), +4 s16 speed, +6 s16 acceleration, +8 s32 bottom y (8.8), +0xC s16 top
	//   speed, +0xE s16 top acceleration (always 0), +0x10 s32 top y (8.8).
	// bone+0xC0 = tpage of the copy (first call). bone+0x92 bit 5 = semi-transparency mode of
	// the cap lines.
	// Every non-frozen draw (rt->boneSkipFlag == 0) integrates every column (speed += accel,
	// y += speed; past the limit the top follows with the bottom's speed) and ++block[0] at the
	// end. Every draw: per visible column a POLY_GT4 (0x34 B, u = column, v 0..0xE0, one tpage
	// per 64 columns, colour 0x80+8n / 0x80-8n / 0x80-8n, n = min(block[0], 15)) from top y to
	// bottom y, and once the limit is passed a DR_MODE + LINE_G2 cap (0x1C B) from (x, top-0x80)
	// black to (x, top) colour 0xFFFF00. Packets through SSIGPU_InsertPrimAltViewport(rt+0x4C).
	// Quirks kept: the GT4 packet's CLUT (+0xE) and pad words (+0x26, +0x32) are not written
	// (stale packet memory, vanilla); the first-call parameter reads use stale upper halves of
	// ecx/edx only below masks that drop them (0xB11C57..0xB11C72).
	// ------------------------------------------------------------------------------------
	static void __cdecl dh_45_ScreenMelt()
	{
		uint8_t *cur = CUR();
		if (PTR(cur, 0xBC) == nullptr)
		{
			uint8_t *prm = PTR(cur, 0xB8);                                   // edi
			uint32_t t = U16(prm, 0);                                        // ecx (was 0)
			uint32_t d = U16(prm, 2);                                        // dx (upper half masked)
			t &= 0xFC0;
			d &= 0x100;
			t |= 0x4000;                                                     // or ch, 0x40
			t >>= 2;
			t |= d;
			t >>= 4;
			U32(cur, 0xC0) = t;
			uint8_t *blk = blob::ArenaAlloc(0x2810);
			PTR(CUR(), 0xBC) = blk;
			uint8_t *col = PTR(CUR(), 0xBC);                                 // esi
			U16(col, 0) = 0;
			int32_t angStep = U16(prm, 0xA);                                 // [ebp-0x1C]
			int32_t spdStep = U16(prm, 6);                                   // [ebp-0x20]
			int32_t angle = U16(prm, 8);                                     // [ebp-4]
			int32_t rndSpd = U16(prm, 0xC);                                  // [ebp-8]
			int32_t spd = U16(prm, 4);                                       // ebx
			int32_t accBase = U16(prm, 0xE);                                 // [ebp-0x18]
			int32_t rndAcc = U16(prm, 0x10);                                 // [ebp-0x14]
			int32_t spdOfs = U16(prm, 0x12);                                 // [ebp-0x10]
			col += 0x10;
			int32_t n = 0x140;                                               // [ebp-0xC]
			do
			{
				U16(col, 0) = 0;
				int32_t s = x::Sin(angle);
				int32_t w = mul32(s, spd) >> 12;                             // edi
				int32_t r = blob::Rand73(rndSpd);
				r = add32(r, spdOfs);
				r = add32(r, spd);
				r = add32(r, w);
				U16(col, 4) = (uint16_t)r;
				int32_t r2 = blob::Rand73(rndAcc);
				r2 = add32(r2, accBase);
				U16(col, 6) = (uint16_t)r2;
				angle = add32(angle, angStep);
				U32(col, 0x10) = 0;
				U32(col, 0xC) = 0;
				U32(col, 8) = 0xE000;
				spd = add32(spd, spdStep);
				col += 0x20;
			} while (--n != 0);
		}
		xl_Nop_B65150();
		cur = CUR();
		uint8_t *blk = PTR(cur, 0xBC);                                       // [ebp-0x20]
		U32(WS(), 0x60) = (uint32_t)U16(PTR(cur, 0xB8), 0x14) << 8;          // fall limit
		U32(WS(), 0x64) = U32(CUR(), 0xC0);                                  // tpage
		U32(WS(), 0x68) = ((uint32_t)U8(CUR(), 0x92) & 0x20) | 0xE1000040;   // cap draw mode
		int32_t fade = S16(blk, 0);
		if (fade >= 0xF) fade = 0xF;
		uint32_t e8 = (uint32_t)fade * 8;                                    // ecx
		uint32_t a = 0x80u - e8;                                             // eax
		uint32_t c = e8 + 0x80u;                                             // ecx
		uint32_t rgb = a | 0x3C00;                                           // or dh, 0x3C
		rgb <<= 8;
		rgb |= a;
		rgb <<= 8;
		rgb |= c;
		uint8_t *col = blk + 0x10;                                           // edi
		U32(WS(), 0x70) = rgb;
		U32(WS(), 0x74) = 0x808080;
		uint8_t *pkt = PTR(CTX(), 0x7C);                                     // esi
		int32_t strip = 0;                                                   // [ebp-8]
		int32_t base = 0;                                                    // [ebp-0xC]
		do
		{
			int32_t i = 0;                                                   // ecx / [ebp-4]
			do
			{
				if (U8(RT(), 0x45) == 0)
				{
					U16(col, 4) = (uint16_t)(U16(col, 4) + U16(col, 6));
					int32_t y = add32(S32(col, 8), S16(col, 4));
					S32(col, 8) = y;
					if (y >= S32(WS(), 0x60))
					{
						U16(col, 0) = 1;
						U16(col, 0xC) = U16(col, 4);
						if (y >= add32(S32(WS(), 0x60), 0x10000)) U16(col, 0) |= 0x8000;
					}
					U16(col, 0xC) = (uint16_t)(U16(col, 0xC) + U16(col, 0xE));
					S32(col, 0x10) = add32(S32(col, 0x10), S16(col, 0xC));
				}
				if (!(U8(col, 1) & 0x80))
				{
					U8(pkt, 3) = 0xC;
					U16(pkt, 0x1A) = (uint16_t)(U16(WS(), 0x64) + (uint16_t)strip);
					uint32_t cc = U32(WS(), 0x70);
					U32(pkt, 0x10) = cc;
					U32(pkt, 4) = cc;
					cc = U32(WS(), 0x74);
					U32(pkt, 0x28) = cc;
					U32(pkt, 0x1C) = cc;
					int32_t xx = add32(base, i);                                 // ebx
					U16(pkt, 0x20) = (uint16_t)xx;
					U16(pkt, 8) = (uint16_t)xx;
					U16(pkt, 0x2C) = (uint16_t)add32(xx, 1);
					U16(pkt, 0x14) = (uint16_t)add32(xx, 1);
					int32_t top = S32(col, 0x10) >> 8;
					U16(pkt, 0x16) = (uint16_t)top;
					U16(pkt, 0xA) = (uint16_t)top;
					int32_t bot = S32(col, 8) >> 8;
					U8(pkt, 0x24) = (uint8_t)i;
					U16(pkt, 0x2E) = (uint16_t)bot;
					U16(pkt, 0x22) = (uint16_t)bot;
					U8(pkt, 0xC) = (uint8_t)i;
					U8(pkt, 0x19) = 0;
					U8(pkt, 0x30) = (uint8_t)(i + 1);
					U8(pkt, 0x18) = (uint8_t)(i + 1);
					U8(pkt, 0xD) = 0;
					U8(pkt, 0x31) = 0xE0;
					U8(pkt, 0x25) = 0xE0;
					x::InsertPrimAltViewport(U32(RT(), 0x4C), pkt);
					pkt += 0x34;
					if (U8(col, 0) & 1)
					{
						U8(pkt, 3) = 6;
						U32(pkt, 8) = 0;
						uint32_t mode = U32(WS(), 0x68);
						U32(pkt, 0xC) = 0x52000000;
						U32(pkt, 4) = mode;
						U32(pkt, 0x14) = 0xFFFF00;
						U16(pkt, 0x18) = (uint16_t)xx;
						U16(pkt, 0x10) = (uint16_t)xx;
						int32_t ty = S32(col, 0x10) >> 8;
						U16(pkt, 0x1A) = (uint16_t)ty;
						U16(pkt, 0x12) = (uint16_t)sub32(ty, 0x80);
						x::InsertPrimAltViewport(U32(RT(), 0x4C), pkt);
						pkt += 0x1C;
					}
				}
				col += 0x20;
			} while (++i < 0x40);
			base += 0x40;
			strip++;
		} while (base < 0x140);
		PTR(CTX(), 0x7C) = pkt;
		if (U8(RT(), 0x45) == 0) U16(blk, 0) = (uint16_t)(U16(blk, 0) + 1);
	}

	// ------------------------------------------------------------------------------------
	// 0xB11100 (Prim[29], C().prim[28]): untinted flat textured triangle (FT3). Record 0x14:
	// +0 u32 colour, +4/+6/+8 u16 UV 0..2, +0xA/+0xC/+0xE u16 vertex offsets, +0x10 u16 CLUT,
	// +0x12 u16 tpage. Rejected when the three clip words share a bit (AND != 0), or NCLIP < 0
	// (always culled, no ws+0x90 test). Packet 0x20 (len 7): +4 colour | 0x24000000 (no ws+0x8C,
	// no lighting), +8/+0x10/+0x18 SXY, +0xC/+0x14/+0x1C UV (no ws+0x98), +0xE CLUT + ws+0x54,
	// +0x16 tpage | ws+0x50. OT key ((d0+d1+d2) / 3) & 0x3FFC, depth keys z0..z2.
	// ------------------------------------------------------------------------------------
	static void __cdecl pr_28_RawFT3()
	{
		uint8_t *ws = WS();                                                  // [ebp-0x10]
		int32_t count = S32(ws, 0x70);                                       // [ebp-0x18]
		uint8_t *pkt = PTR(ws, 0x60);                                        // esi
		uint32_t ot = U32(ws, 0x5C);                                         // [ebp-0x30]
		uint8_t *rec = PTR(ws, 0x6C);                                        // edi
		do
		{
			uint8_t *vb = PTR(ws, 0x7C);
			uint32_t o0 = U16(rec, 0xA);
			uint32_t o1 = U16(rec, 0xC);
			uint32_t o2 = U16(rec, 0xE);
			int32_t z0 = DepthKey(o0);
			int32_t z1 = DepthKey(o1);
			int32_t z2 = DepthKey(o2);
			uint8_t *p2 = vb + o2;
			uint8_t *p0 = vb + o0;
			uint8_t *p1 = vb + o1;
			if ((uint16_t)(U16(p2, 6) & U16(p1, 6)) & U16(p0, 6)) goto next;
			{
				uint32_t s0 = U32(p0, 0);
				uint32_t s1 = U32(p1, 0);
				uint32_t s2 = U32(p2, 0);
				U32(pkt, 8) = s0;
				U32(pkt, 0x10) = s1;
				U32(pkt, 0x18) = s2;
				if (Nclip(s0, s1, s2) < 0) goto next;
				int32_t sum = (int32_t)((uint32_t)U16(p2, 4) + U16(p1, 4) + U16(p0, 4));
				int32_t key = Div3(sum);
				U8(pkt, 3) = 7;
				U16(pkt, 0x16) = (uint16_t)(U32(ws, 0x50) | U16(rec, 0x12));
				U16(pkt, 0xE) = (uint16_t)add32(U16(rec, 0x10), S32(ws, 0x54));
				U16(pkt, 0xC) = U16(rec, 4);
				U16(pkt, 0x14) = U16(rec, 6);
				U16(pkt, 0x1C) = U16(rec, 8);
				U32(pkt, 4) = U32(rec, 0) | 0x24000000;
				x::InsertPrimDepthKeys(ot + ((uint32_t)key & 0x3FFC), pkt, z0, z1, z2, 0);
				pkt += 0x20;
			}
		next:
			rec += 0x14;
		} while (--count > 0);
		PTR(ws, 0x60) = pkt;
	}

	// ------------------------------------------------------------------------------------
	// 0xB11580 (Prim[39], C().prim[38]): untinted flat textured quad (FT4). Record 0x18: +0 u32
	// colour, +4/+6/+8/+0xA u16 UV 0..3, +0xC/+0xE/+0x10/+0x12 u16 vertex offsets, +0x14 u16
	// CLUT, +0x16 u16 tpage. Rejected when the four clip words share a bit, or NCLIP(v0,v1,v2)
	// < 0. Packet 0x28 (len 9): +4 colour | 0x2C000000, +8/+0x10/+0x18/+0x20 SXY,
	// +0xC/+0x14/+0x1C/+0x24 UV, +0xE CLUT + ws+0x54, +0x16 tpage | ws+0x50. OT key
	// ((d0+d1+d2+d3) >> 2) & 0x3FFC. (The key sum at 0xB11724..0xB11741 loads the u16 depths
	// into registers whose upper halves hold MAC0 / vertex pointers; those upper bits only reach
	// sum bits >= 16, which the >> 2 & 0x3FFC drops: the plain u16 sum is identical.)
	// ------------------------------------------------------------------------------------
	static void __cdecl pr_38_RawFT4()
	{
		uint8_t *ws = WS();                                                  // [ebp-0x14]
		int32_t count = S32(ws, 0x70);                                       // [ebp-0x1C]
		uint32_t ot = U32(ws, 0x5C);                                         // [ebp-0x24]
		uint8_t *pkt = PTR(ws, 0x60);                                        // esi
		uint8_t *rec = PTR(ws, 0x6C);                                        // edi
		do
		{
			uint8_t *vb = PTR(ws, 0x7C);
			uint32_t o0 = U16(rec, 0xC);
			uint32_t o1 = U16(rec, 0xE);
			uint32_t o2 = U16(rec, 0x10);
			uint32_t o3 = U16(rec, 0x12);
			int32_t z0 = DepthKey(o0);
			int32_t z1 = DepthKey(o1);
			int32_t z2 = DepthKey(o2);
			int32_t z3 = DepthKey(o3);
			uint8_t *p2 = vb + o2;
			uint8_t *p0 = vb + o0;
			uint8_t *p3 = vb + o3;
			uint8_t *p1 = vb + o1;
			if ((uint16_t)(U16(p3, 6) & U16(p2, 6) & U16(p1, 6)) & U16(p0, 6)) goto next;
			{
				uint32_t s2 = U32(p2, 0);
				uint32_t s1 = U32(p1, 0);
				uint32_t s0 = U32(p0, 0);
				uint32_t s3 = U32(p3, 0);
				U32(pkt, 0x10) = s1;
				U32(pkt, 8) = s0;
				U32(pkt, 0x18) = s2;
				U32(pkt, 0x20) = s3;
				if (Nclip(s0, s1, s2) < 0) goto next;
				uint32_t sum = (uint32_t)U16(p3, 4) + U16(p2, 4) + U16(p1, 4) + U16(p0, 4);
				uint32_t key = ((sum >> 2) & 0x3FFC) + ot;
				U8(pkt, 3) = 9;
				U16(pkt, 0x16) = (uint16_t)(U32(ws, 0x50) | U16(rec, 0x16));
				U16(pkt, 0xE) = (uint16_t)add32(U16(rec, 0x14), S32(ws, 0x54));
				U16(pkt, 0xC) = U16(rec, 4);
				U16(pkt, 0x14) = U16(rec, 6);
				U16(pkt, 0x1C) = U16(rec, 8);
				U16(pkt, 0x24) = U16(rec, 0xA);
				U32(pkt, 4) = U32(rec, 0) | 0x2C000000;
				x::InsertPrimDepthKeys(key, pkt, z0, z1, z2, z3);
				pkt += 0x28;
			}
		next:
			rec += 0x18;
		} while (--count > 0);
		PTR(ws, 0x60) = pkt;
	}

	// ------------------------------------------------------------------------------------
	// 0xB117F0 (Prim[40], C().prim[39]): untinted Gouraud textured quad (GT4). Record 0x24:
	// +0/+4/+8/+0xC u32 colour 0..3, +0x10/+0x12/+0x14/+0x16 u16 UV 0..3, +0x18/+0x1A/+0x1C/+0x1E
	// u16 vertex offsets, +0x20 u16 CLUT, +0x22 u16 tpage. Rejected when the four clip words
	// share a bit, or NCLIP(v0,v1,v2) < 0. Packet 0x34 (len 0xC): +4 colour0 | 0x3C000000,
	// +0x10/+0x1C/+0x28 colour 1..3 (raw), +8/+0x14/+0x20/+0x2C SXY, +0xC/+0x18/+0x24/+0x30 UV,
	// +0xE CLUT + ws+0x54, +0x1A tpage | ws+0x50. OT key ((d0+d1+d2+d3) >> 2) & 0x3FFC (same
	// upper-half remark as pr_38, 0xB11989..0xB119AC).
	// ------------------------------------------------------------------------------------
	static void __cdecl pr_39_RawGT4()
	{
		uint8_t *ws = WS();                                                  // [ebp-0x14]
		int32_t count = S32(ws, 0x70);                                       // [ebp-0x1C]
		uint32_t ot = U32(ws, 0x5C);                                         // [ebp-0x24]
		uint8_t *pkt = PTR(ws, 0x60);                                        // esi
		uint8_t *rec = PTR(ws, 0x6C);                                        // edi
		do
		{
			uint8_t *vb = PTR(ws, 0x7C);
			uint32_t o0 = U16(rec, 0x18);
			uint32_t o1 = U16(rec, 0x1A);
			uint32_t o2 = U16(rec, 0x1C);
			uint32_t o3 = U16(rec, 0x1E);
			int32_t z0 = DepthKey(o0);
			int32_t z1 = DepthKey(o1);
			int32_t z2 = DepthKey(o2);
			int32_t z3 = DepthKey(o3);
			uint8_t *p2 = vb + o2;
			uint8_t *p0 = vb + o0;
			uint8_t *p3 = vb + o3;
			uint8_t *p1 = vb + o1;
			if ((uint16_t)(U16(p3, 6) & U16(p2, 6) & U16(p1, 6)) & U16(p0, 6)) goto next;
			{
				uint32_t s2 = U32(p2, 0);
				uint32_t s1 = U32(p1, 0);
				uint32_t s0 = U32(p0, 0);
				uint32_t s3 = U32(p3, 0);
				U32(pkt, 0x14) = s1;
				U32(pkt, 8) = s0;
				U32(pkt, 0x20) = s2;
				U32(pkt, 0x2C) = s3;
				if (Nclip(s0, s1, s2) < 0) goto next;
				uint32_t sum = (uint32_t)U16(p3, 4) + U16(p2, 4) + U16(p1, 4) + U16(p0, 4);
				uint32_t key = ((sum >> 2) & 0x3FFC) + ot;
				U8(pkt, 3) = 0xC;
				U16(pkt, 0x1A) = (uint16_t)(U32(ws, 0x50) | U16(rec, 0x22));
				U16(pkt, 0xE) = (uint16_t)add32(U16(rec, 0x20), S32(ws, 0x54));
				uint16_t uv2 = U16(rec, 0x14);
				uint16_t uv3 = U16(rec, 0x16);
				U16(pkt, 0x18) = U16(rec, 0x12);
				U16(pkt, 0xC) = U16(rec, 0x10);
				U16(pkt, 0x24) = uv2;
				U16(pkt, 0x30) = uv3;
				uint32_t c3 = U32(rec, 0xC);
				uint32_t c2 = U32(rec, 8);
				uint32_t c1 = U32(rec, 4);
				uint32_t c0 = U32(rec, 0);
				U32(pkt, 0x1C) = c2;
				U32(pkt, 0x10) = c1;
				U32(pkt, 0x28) = c3;
				U32(pkt, 4) = c0 | 0x3C000000;
				x::InsertPrimDepthKeys(key, pkt, z0, z1, z2, z3);
				pkt += 0x34;
			}
		next:
			rec += 0x24;
		} while (--count > 0);
		PTR(ws, 0x60) = pkt;
	}
}
	// installs the ports into a clone's tables (called after init_clone)
	void apply_cerberus(Clone &c)
	{
		c.draw[45] = part_cerberus::dh_45_ScreenMelt;   // 0xB11C30
		c.prim[28] = part_cerberus::pr_28_RawFT3;       // 0xB11100
		c.prim[38] = part_cerberus::pr_38_RawFT4;       // 0xB11580
		c.prim[39] = part_cerberus::pr_39_RawGT4;       // 0xB117F0
	}
}
}
// ==== END clone handler parts ====




namespace ff8fx
{
namespace gfc
{
namespace cerberus
{
	static Clone g_c = {};

	static void describe(Clone &c)
	{
		c.name = "203 Cerberus";
		c.effect_id = 203;
		c.vm_table = 0x1873528;
		c.bone_table = 0x1873198;
		c.prim_table = 0x18731E0;
		c.prim_size = 0x18732D0;
		c.spr_table = 0x18732E4;
		c.ptype_table = 0x1873310;
		c.pop_table = 0x1873324;
		c.draw_table = 0x1873384;
		c.attr_16A = 0x18734EE;
		c.attr_184 = 0x1873508;
		c.attr_186 = 0x187350A;
		c.attr_194 = 0x1873518;
		c.attr_19C = 0x1873520;
		c.desc = 0x1872EF8;
		c.ptr_block = 0x1873170;
		c.queue = 0x2796DA8;
		c.file00 = 0x2796DDC;
		c.file01 = 0x2796DD8;
		c.tick = 0xB0C820;
		c.load_cb = 0xB143F0;
		c.lit_dispatcher = false;
		c.bone_count = 18;
	}

	static uint32_t __cdecl SequenceTask(TaskNode *)
	{
		return SequenceTick(g_c);
	}
}
}

	void register_gfc_cerberus()
	{
		using namespace gfc;
		cerberus::describe(cerberus::g_c);
		init_clone(cerberus::g_c, nullptr, 0);
		apply_cerberus(cerberus::g_c);
		apply_shared_ribbon(cerberus::g_c);
		apply_shared_misc(cerberus::g_c);
		register_port(0xB0C820, (void *)cerberus::SequenceTask, "GFC203 Cerberus SequenceTick", 203);
		// 30 fps layer: see mag_cerberus_held.inc
		FX_HELD(register_gfc_cerberus_held();)
	}
}

#ifdef FF8_FX_HELD
#include "mag_cerberus_held.inc"
#endif
