/****************************************************************************/
//    Copyright (C) 2026 HobbitDur                                          //
//                                                                          //
//    This file is part of FFNx                                             //
//                                                                          //
//    FFNx is free software: you can redistribute it and/or modify          //
//    it under the terms of the GNU General Public License as published by  //
//    the Free Software Foundation, either version 3 of the License         //
//                                                                          //
//    FFNx is distributed in the hope that it will be useful,               //
//    but WITHOUT ANY WARRANTY; without even the implied warranty of        //
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         //
//    GNU General Public License for more details.                          //
/****************************************************************************/

// Effect 006: Leviathan (cinematic-engine GF, module 0xB58000..0xB65150, script data
// magic/MAG005_B.00/.01, streamed parts battle/mag005_b.02..). One clone of the GF cinematic
// engine (gfc_engine.cpp); this file holds the clone descriptor and the ports of the handlers that
// are not byte clones of the generic (Ifrit) ones.

#include "gfc_engine.h"

#ifdef FF8_FX_HELD
#include "mag_leviathan_held.h"
#endif

// ==== BEGIN clone handler parts (generated by integrate.py) ====
// ---- part lev_a
namespace ff8fx
{
namespace gfc
{
namespace part_lev_a
{
	// ------------------------------------------------------------------------------------
	// local wrappers / helpers
	// ------------------------------------------------------------------------------------
	// 0x56C8C0 RotTransPers(v, sxy, p, flag): GTE_LoadV0(v); RTPS; SXY2 -> *sxy (then both s16
	// halves >>= 3); IR0 (0x1CA8A30) -> *p; FLAG -> *flag; returns SZ3 / 4 (full dword, written
	// by 0x45E250 into the v argument slot and read back). GTE + the three destinations only.
	static inline int32_t xl_RotTransPers(const void *v, void *sxy, void *p, void *flag)
	{
		return x::f<int32_t (__cdecl *)(const void *, void *, void *, void *)>(0x56C8C0)(v, sxy, p, flag);
	}

	// 0xB65810 (shared blob): off-screen pass of the Leviathan water: ws+0xF0 = arena block
	// {+0 aux OT (0x400 entries) or 0, +4 OT (0x1000 entries) or 0, +8 packet buffer, +0xC size,
	// +0x10.. two DRAWENVs}; ws+0xD0/0xD2 = screen position, ws+0xD4/0xD6 = size. Sets two draw
	// environments (0x45C0F0), clears OTs (0x45D530), poses and renders the party battle models
	// (0x508C90 / 0x5095B0 / 0x5099D0 on 0x1D989A4.. / 0x1D989FC..) and executes the OTs
	// (0x45CEE0): GPU work + battle model writes.
	static inline void xl_OffscreenRender_B65810()
	{
		// 30 fps layer: see gfc_engine_held.h
		FX_HELD(if (held_predicting()) return;)
		x::f<int32_t (__cdecl *)()>(0xB65810)();
	}

	// mov [t], 0x55555556; imul dword [t]; ...; sar v, 0x1F; sub hi, v
	static inline int32_t Div3(int32_t v)
	{
		int32_t hi = (int32_t)(((int64_t)v * (int64_t)0x55555556) >> 32);
		return sub32(hi, v >> 31);
	}

	// fild qword [u16 zero-extended DEPTHARR[off >> 3], high dword 0]; fmul dword [0x1877DA8];
	// call __ftol (low dword kept)
	static inline int32_t DepthKey(uint32_t off)
	{
		uint32_t v = DEPTHARR()[off >> 3] & 0xFFFF;
		return (int32_t)(int64_t)((double)v * (double)FLT_1877DA8());
	}

	// C '/' by 2^k on int32 (cdq; and edx, 2^k-1; add eax, edx; sar eax, k)
	static inline int32_t DivPow2(int32_t v, int k)
	{
		uint32_t bias = (uint32_t)(v >> 31) & ((1u << k) - 1u);
		return (int32_t)((uint32_t)v + bias) >> k;
	}

	// 32-bit address arithmetic (lea edi, [edi + edx*2] with a possibly negative edx)
	static inline uint8_t *PADD(uint8_t *p, int32_t n) { return (uint8_t *)((uint32_t)p + (uint32_t)n); }

	// ------------------------------------------------------------------------------------
	// 0xB59150 (Draw 17 RippleTextureUpload): horizontal sine-ripple of a texture, uploaded to
	// VRAM. bone+0xB8 -> {s16 alt texture id, s16 vram x, s16 vram y}. First draw: temp buffer
	// (w * h halfwords) allocated in the arena, pointer kept at bone+0xBC. Row y of the texture
	// is rotated right by ((bone+0x94 + (cos(phase) * bone+0x8C) >> 20) & (w - 1)) texels,
	// phase = bone+0x8E, += bone+0x90 per row; then the buffer is uploaded (one rect of the
	// VRAM rect ring). Draws no primitive.
	// ws: +0x60 dst row, +0x64 src row, +0x68 rect, +0x6C w-1, +0x70 offset, +0x74 amplitude,
	// +0x78 w, +0x7C rows left, +0x80 buffer, +0x84 row bytes, +0x88 phase, +0x8C phase step.
	// ------------------------------------------------------------------------------------
	static void __cdecl dh_17_RippleTextureUpload()
	{
		// 30 fps layer: see mag_leviathan_held.inc
		FX_HELD(if (held_active()) return;)
		uint8_t *arg = PTR(CUR(), 0xB8);                                  // edi
		blob::ReadAltTexture(S16(arg, 0));                                // ws+0xF0..0xFC
		U32(WS(), 0x64) = U32(WS(), 0xFC);                                // texel data
		uint8_t *tex = PTR(WS(), 0xF0);                                   // esi
		if (U32(CUR(), 0xBC) == 0)
		{
			int32_t n = shl32(mul32(S16(tex, 6), S16(tex, 4)), 1);
			uint8_t *buf = blob::ArenaAlloc(n);
			PTR(CUR(), 0xBC) = buf;
		}
		U32(WS(), 0x60) = U32(CUR(), 0xBC);
		{
			uint8_t *w = WS();
			U32(w, 0x80) = U32(w, 0x60);
		}
		uint8_t *rect = blob::VramRectRing();
		PTR(WS(), 0x68) = rect;
		rect = PTR(WS(), 0x68);                                           // eax
		U16(rect, 0) = U16(arg, 2);
		U16(rect, 2) = U16(arg, 4);
		uint16_t wd = U16(tex, 4);
		U16(rect, 4) = wd;
		S32(WS(), 0x78) = (int16_t)wd;
		int32_t w32 = S32(WS(), 0x78);                                    // ecx
		uint16_t ht = U16(tex, 6);
		U16(rect, 6) = ht;
		S32(WS(), 0x7C) = (int16_t)ht;
		int32_t mask = sub32(w32, 1);                                     // eax
		S32(WS(), 0x6C) = mask;
		S32(WS(), 0x70) = (int32_t)S16(CUR(), 0x94) & mask;
		S32(WS(), 0x84) = add32(w32, w32);
		S32(WS(), 0x74) = S16(CUR(), 0x8C);
		S32(WS(), 0x88) = S16(CUR(), 0x8E);
		S32(WS(), 0x8C) = S16(CUR(), 0x90);
		uint8_t *w = WS();                                                // eax
		if (S32(w, 0x7C) > 0)
		{
			do
			{
				uint8_t *dst = PTR(w, 0x60);                              // edi
				uint8_t *src = PTR(w, 0x64);                              // esi
				int32_t c = x::Cos(S32(w, 0x88));
				w = WS();                                                 // ecx
				int32_t off = add32(S32(w, 0x70), mul32(c, S32(w, 0x74)) >> 20);   // edx
				off &= S32(w, 0x6C);
				int32_t n = sub32(S32(w, 0x78), off);                     // eax
				dst = PADD(dst, shl32(off, 1));
				if (n > 0)
				{
					do
					{
						U16(dst, 0) = U16(src, 0);
						src += 2;
						dst += 2;
					} while (--n != 0);
					w = WS();
				}
				uint8_t *d2 = PTR(w, 0x60);                               // eax
				if (off > 0)
				{
					do
					{
						U16(d2, 0) = U16(src, 0);
						src += 2;
						d2 += 2;
					} while (--off != 0);
					w = WS();
				}
				int32_t step = S32(w, 0x84);                              // eax
				S32(w, 0x60) = add32(S32(w, 0x60), step);
				w = WS();
				S32(w, 0x64) = add32(S32(w, 0x64), step);
				w = WS();
				S32(w, 0x88) = add32(S32(w, 0x88), S32(w, 0x8C));
				w = WS();
				S32(w, 0x7C) = S32(w, 0x7C) - 1;
				w = WS();
			} while (S32(w, 0x7C) > 0);
		}
		x::QueueVramUpload(PTR(w, 0x68), PTR(w, 0x80));
	}

	// ------------------------------------------------------------------------------------
	// 0xB594B0 (Draw 18 WaterColumn): procedural water column, 17 rings x 32 columns of
	// POLY_GT4 (0x34 B, len 0xC) inserted with SSIGPU_InsertPrimAltViewport.
	// bone+0xB8 -> {u16 vram x, u16 vram y, u16 tpage bits, s16 reference bone}. First draw
	// (bone+0xBC == 0): state block 0xA0 B in the arena (bone+0xBC): +4 reference bone, +6 = 0x20,
	// +0x20 s16[32] wave heights, +0x60 s16[32] radii (both rewritten every draw); bone+0x92 =
	// tpage word (texture page from vram x/y | old bits 0x60 | arg+4).
	// Radii: column i -> C = i * (bone+0x90 * ref+0x98) / 32, B = i * (bone+0x90 << 8) / 32; ring
	// table A (at the arena top, ws+0x80, unallocated scratch) = 10 rings of 32 dwords for C
	// (+0x000) and B (+0x500): pairs (cos, sin) * radius at angles 0, 0x100, 0x200, 0x300, 0x400;
	// A+0xA00 = wave heights (sin(phase >> 4) * (amp >> 4) >> 20; amp from bone+0x8C << 8, step
	// bone+0x8E << 4; phase from ref+0x8C << 8, velocity ref+0x8E, accel ref+0x90), A+0xB00 = s16
	// OTZ per vertex (32 per ring). Row r = 1..16 uses ring pair tbl[r] & 7 and quadrant
	// (tbl[r] >> 6) & 3 (signs of x / z and of the UV offsets), tbl = draw_table - 440.
	// UV = (ref+0x94 + B-ring x, ref+0x96 + B-ring z); colour = bone+0xCC & 0x2FFFFFF | 0x3C000000
	// (semi-transparent GT4), tpage = bone+0x92, clut = bone+0x9A.
	// Vanilla quirk (0xB59AD9 and 0xB59C44 / 0xB59DB1 / 0xB59F19 / 0xB5A085): the depth row
	// stride is 16 entries (edi - 0x20 / edi - 0x22) while a ring stores 32 OTZ -> the quad depth
	// averages the OTZ of columns j-16 / j-17 (wrapping into the previous ring for j < 17), and
	// column 0 of every ring copies the OTZ 16 entries back. Reproduced as is.
	// Packet cursor ctx+0x7C ends at the start of the last ring's packets (they only carried the
	// vertices); packet 31 of every ring is never inserted. ws+0x20/0x30/0x40/0x50 are zeroed after
	// every ring (vanilla).
	// ------------------------------------------------------------------------------------
	static void __cdecl dh_18_WaterColumn()
	{
		if (U32(CUR(), 0xBC) == 0)
		{
			uint8_t *nb = blob::ArenaAlloc(0xA0);
			PTR(CUR(), 0xBC) = nb;
			uint8_t *blk0 = PTR(CUR(), 0xBC);                             // ecx
			uint8_t *arg = PTR(CUR(), 0xB8);                              // eax
			uint16_t ref = U16(arg, 6);
			U16(blk0, 6) = 0x20;
			U16(blk0, 4) = ref;
			uint32_t a0 = U16(arg, 0);
			uint32_t a2 = U16(arg, 2);
			uint8_t *cur = CUR();
			uint32_t b = U8(cur, 0x92) & 0x60u;
			uint32_t e = (a0 >> 2) & 0x3F0u;                              // sar edx, 2 (bits 6..11 of a0)
			uint16_t dx = (uint16_t)(e | (a2 & 0x100u));
			dx = (uint16_t)((int16_t)dx >> 4);                            // sar dx, 4
			dx = (uint16_t)(dx | b);
			dx = (uint16_t)(dx | U16(arg, 4));
			U16(cur, 0x92) = dx;
		}
		uint8_t *blk = PTR(CUR(), 0xBC);                                  // [ebp-0x14]
		uint8_t *bone2 = blob::GetBone(S16(blk, 4));                      // [ebp-0x18]
		uint8_t *rad16 = blk + 0x60;                                      // ebx
		PTR(WS(), 0x80) = PTR(CTX(), 0x74);
		S32(WS(), 0x60) = S16(CUR(), 0x90);
		S32(WS(), 0x64) = S16(bone2, 0x98);
		S32(WS(), 0x68) = shl32(S16(CUR(), 0x8C), 8);
		S32(WS(), 0x6C) = shl32(S16(CUR(), 0x8E), 4);
		S32(WS(), 0x70) = shl32(S16(bone2, 0x8C), 8);
		S32(WS(), 0x74) = S16(bone2, 0x8E);
		S32(WS(), 0x78) = S16(bone2, 0x90);
		S32(WS(), 0x84) = S16(CUR(), 0x92);
		S32(WS(), 0x88) = S16(CUR(), 0x9A);
		U32(WS(), 0x8C) = (U32(CUR(), 0xCC) & 0x2FFFFFFu) | 0x3C000000u;

		// --- radii (0xB5965D) ---
		{
			uint8_t *w = WS();
			int32_t k60 = S32(w, 0x60);
			int32_t stepC = mul32(S32(w, 0x64), k60);                    // edi
			uint8_t *a = PTR(w, 0x80);                                    // ecx
			int32_t stepB = shl32(k60, 8);                                // [ebp-0x10]
			int32_t accB = 0, accC = 0;                                   // [ebp-8], [ebp-0xC]
			for (int i = 0; i < 32; i++)
			{
				int32_t c = DivPow2(accC, 5);
				U16(rad16, 2 * i) = (uint16_t)DivPow2(c, 8);
				S32(a, 4 * i) = c;
				S32(a, 0x500 + 4 * i) = DivPow2(accB, 5);
				S32(a, 0x80 + 4 * i) = 0;
				S32(a, 0x580 + 4 * i) = 0;
				accB = add32(accB, stepB);
				accC = add32(accC, stepC);
			}
		}
		// --- rotated rings (0xB596D9, 0xB5975F, 0xB597E4) ---
		for (int k = 1; k <= 3; k++)
		{
			int32_t ang = k * 0x100;
			uint8_t *p = PTR(WS(), 0x80);                                 // esi
			for (int i = 0; i < 32; i++)
			{
				int32_t r = S32(p, 0);                                    // edi
				int32_t v = x::Cos(ang);
				S32(p, 0x100 * k) = mul32(v >> 4, r) >> 16;
				v = x::Sin(ang);
				int32_t t = mul32(v >> 4, r);
				r = S32(p, 0x500);
				S32(p, 0x100 * k + 0x80) = t >> 16;
				v = x::Cos(ang);
				S32(p, 0x500 + 0x100 * k) = mul32(v >> 4, r) >> 16;
				v = x::Sin(ang);
				S32(p, 0x580 + 0x100 * k) = mul32(v >> 4, r) >> 16;
				p += 4;
			}
		}
		// --- angle 0 / 0x400 rings, radii / 256 (0xB5986A) ---
		{
			uint8_t *p = PTR(WS(), 0x80);                                 // ecx
			for (int i = 0; i < 32; i++)
			{
				int32_t v = S32(p, 0);
				S32(p, 0x400) = 0;
				S32(p, 0x900) = 0;
				v = DivPow2(v, 8);
				S32(p, 0) = v;
				S32(p, 0x480) = v;
				v = DivPow2(S32(p, 0x500), 8);
				S32(p, 0x500) = v;
				S32(p, 0x980) = v;
				p += 4;
			}
		}
		// --- wave heights (0xB598C3) ---
		{
			uint8_t *w = WS();
			uint8_t *p = PTR(w, 0x80) + 0xA00;                            // esi
			int32_t stepAmp = S32(w, 0x6C);                               // [ebp-0x10]
			int32_t amp = S32(w, 0x68);                                   // edi
			int32_t vel = S32(w, 0x74);                                   // ebx
			uint8_t *h16 = blk + 0x20;                                    // [ebp-4]
			int32_t phase = S32(w, 0x70);                                 // [ebp-8]
			int32_t accel = S32(w, 0x78);                                 // [ebp-0x14]
			for (int i = 0; i < 32; i++)
			{
				int32_t s = x::Sin(phase >> 4);
				int32_t v = mul32(s, amp >> 4) >> 20;
				p += 4;
				U16(h16, 0) = (uint16_t)v;
				S32(p, -4) = (int16_t)v;
				amp = add32(amp, stepAmp);
				vel = add32(vel, accel);
				h16 += 2;
				phase = add32(phase, vel);
			}
		}

		h_B27000();                                                       // 0xB5A150 (== Ifrit 0xB27000)
		int32_t eu = S16(bone2, 0x94);                                    // [ebp-8]
		int32_t ev = S16(bone2, 0x96);                                    // [ebp-0xC]
		uint8_t *pkt = PTR(CTX(), 0x7C);                                  // esi
		uint8_t *A = PTR(WS(), 0x80);                                     // ebx (walks 4 per column)
		U16(WS(), 0xD0) = 0;

		// --- ring 0 (0xB5997E): vertices only, into packets 0..31 of row 0 ---
		uint8_t *dep = A + 0xB00;                                         // edi
		U16(WS(), 0xD4) = U16(A, 0);
		U16(WS(), 0xD2) = U16(A, 0xA00);
		int32_t otz;
		{
			uint8_t *w = WS();
			otz = xl_RotTransPers(w + 0xD0, pkt + 8, w + 0xFC, w + 0xFC);
		}
		U8(pkt, 0xC) = (uint8_t)(U8(A, 0x500) + (uint8_t)eu);
		U8(pkt, 0xD) = (uint8_t)(U8(A, 0x580) + (uint8_t)ev);
		U16(dep, 0) = (uint16_t)otz;
		dep += 2;
		for (int j = 1; j < 32; j++)
		{
			uint8_t *pk = pkt + 0x34 * j;
			U16(WS(), 0xD4) = U16(A, 4 * j);
			U16(WS(), 0xD2) = U16(A, 0xA00 + 4 * j);
			{
				uint8_t *w = WS();
				otz = xl_RotTransPers(w + 0xD0, pk + 8, w + 0xFC, w + 0xFC);
			}
			U32(pk, -0x20) = U32(pk, 8);                                  // prev col xy1
			uint8_t u = (uint8_t)(U8(A, 0x500 + 4 * j) + (uint8_t)eu);
			U8(pk, 0xC) = u;
			U8(pk, -0x1C) = u;                                            // prev col uv1.u
			uint8_t v = (uint8_t)(U8(A, 0x580 + 4 * j) + (uint8_t)ev);
			U8(pk, 0xD) = v;
			U8(pk, -0x1B) = v;                                            // prev col uv1.v
			U16(dep, 0) = (uint16_t)otz;
			dep += 2;
		}

		// --- rings 1..16 (0xB59A8C): vertices of ring r complete the quads of ring r-1 ---
		uint8_t *row = pkt + 0x680;                                       // esi
		const uint8_t *tbl = (const uint8_t *)(C().draw_table - 440);     // Leviathan 0x1877508
		S32(WS(), 0x7C) = 1;
		while (S32(WS(), 0x7C) < 0x11)
		{
			int32_t r = S32(WS(), 0x7C);
			uint32_t t = tbl[r];                                          // bl
			uint8_t *prev = row - 0x680;
			A = PTR(WS(), 0x80);                                          // eax
			uint32_t xy = U32(prev, 8);
			U32(row, 8) = xy;
			U32(prev, 0x20) = xy;
			t &= 7;
			int16_t uv0 = S16(prev, 0xC);
			U16(row, 0xC) = (uint16_t)uv0;
			U16(prev, 0x24) = (uint16_t)uv0;
			U16(dep, 0) = U16(dep, -0x20);                                // quirk: 16 entries back
			uint8_t *ring = A + (t << 8) + 4;                             // ebx
			uint8_t *hgt = A + 0xA00 + 4;                                 // [ebp-4]
			uint32_t q = ((uint32_t)tbl[S32(WS(), 0x7C)] >> 6) & 3;       // cl (re-read), sar 6, & 3
			dep += 2;
			uint8_t *pk = row + 0x34;                                     // esi
			// the four cases of the listing (q = 3 0xB59B25, 2 0xB59C9F, 1 0xB59E06, 0 0xB59F7B)
			// differ only in the signs below; stores and calls are in the same order
			for (int cnt = 0x1F; cnt != 0; cnt--)
			{
				uint16_t zx = U16(ring, 0);
				U16(WS(), 0xD4) = (q & 1) ? (uint16_t)(0u - zx) : zx;
				U16(WS(), 0xD2) = U16(hgt, 0);
				uint16_t xx = U16(ring, 0x80);
				U16(WS(), 0xD0) = (q & 2) ? (uint16_t)(0u - xx) : xx;
				{
					uint8_t *w = WS();
					otz = xl_RotTransPers(w + 0xD0, w + 0xF0, w + 0xFC, w + 0xFC);
				}
				uint32_t sxy = U32(WS(), 0xF0);
				U32(pk, -0x688) = sxy;                                    // prev row, prev col xy3
				U32(pk, -0x660) = sxy;                                    // prev row xy2
				U32(pk, -0x20) = sxy;                                     // prev col xy1
				U32(pk, 8) = sxy;                                         // xy0
				int32_t sv = S16(ring, 0x580), su = S16(ring, 0x500);
				int32_t vv = (q & 2) ? sub32(ev, sv) : add32(sv, ev);
				int32_t uu = (q & 1) ? sub32(eu, su) : add32(su, eu);
				uint16_t uv = (uint16_t)(shl32(vv, 8) | uu);
				U16(pk, -0x684) = uv;                                     // prev row, prev col uv3
				U16(pk, -0x65C) = uv;                                     // prev row uv2
				U16(pk, -0x1C) = uv;                                      // prev col uv1
				U16(pk, 0xC) = uv;                                        // uv0
				U16(dep, 0) = (uint16_t)otz;
				uint8_t *quad = pk - 0x6B4;                               // prev row, prev col: complete
				U8(quad, 3) = 0xC;
				U16(quad, 0x1A) = U16(WS(), 0x84);                        // tpage
				U16(quad, 0xE) = U16(WS(), 0x88);                         // clut
				uint32_t col = U32(WS(), 0x8C);
				U32(quad, 0x28) = col;
				U32(quad, 0x1C) = col;
				U32(quad, 0x10) = col;
				U32(quad, 4) = col;
				int32_t sum = add32(add32(add32(S16(dep, -0x20), otz), S16(dep, -0x22)), S16(dep, -2));
				uint32_t slot = ((uint32_t)DivPow2(sum, 2) & 0xFFFFFFFCu) + U32(RT(), 0x4C);
				x::InsertPrimAltViewport(slot, quad);
				pk += 0x34;
				ring += 4;
				hgt += 4;
				dep += 2;
			}
			row = pk;
			U32(WS(), 0x20) = 0;
			U32(WS(), 0x30) = 0;
			U32(WS(), 0x40) = 0;
			U32(WS(), 0x50) = 0;
			S32(WS(), 0x7C) = S32(WS(), 0x7C) + 1;
		}
		PTR(CTX(), 0x7C) = row - 0x680;
	}

	// ------------------------------------------------------------------------------------
	// 0xB5C720 (Prim[2], C().prim[2]): semi-transparent Gouraud triangle lit by one normal with
	// the current light setup, followed by a draw-mode packet in the same OT slot.
	// Record 0x14: +0/+4/+8 u32 colour 0..2, +0xC u16 normal byte offset (into ws+0x78),
	// +0xE/+0x10/+0x12 u16 vertex offsets.
	// Packets: G3 0x1C (len 6, code 0x32: RGB at +4/+0xC/+0x14, SXY at +8/+0x10/+0x18), then
	// draw mode 0xC (tag 0x02000000, +4 ws+0x50, +8 0), both InsertPrimDepthKeys(ot + key, ..,
	// z0, z1, z2, 0), key = (sum of the three vertex depth words / 3) & 0x3FFC.
	// Vanilla: overwrites ws+0x84 (material colour) with 0x32000000 for the rest of the mesh draw.
	// ------------------------------------------------------------------------------------
	static void __cdecl pr_02_NormalLitG3()
	{
		U32(WS(), 0x84) = 0x32000000;
		uint8_t *ws = WS();                                               // edi (kept all along)
		uint32_t ot = U32(ws, 0x5C);                                      // [ebp-0x40]
		uint8_t *pkt = PTR(ws, 0x60);                                     // esi
		int32_t count = S32(ws, 0x70);                                    // [ebp-0x34]
		uint8_t *rec = PTR(ws, 0x6C);                                     // ebx
		uint32_t nocull = U32(ws, 0x90) & 0x10;                           // [ebp-0x38]
		uint8_t *c0 = pkt + 4;                                            // [ebp-0x14]
		uint8_t *c2 = pkt + 0x14;                                         // [ebp-0x10]
		uint8_t *c1 = pkt + 0xC;                                          // [ebp-0xC]
		U32(ws, 0xF0) = 0;
		do
		{
			uint8_t *vb = PTR(ws, 0x7C);
			uint32_t o1 = U16(rec, 0x10);
			uint32_t o0 = U16(rec, 0xE);
			uint32_t o2 = U16(rec, 0x12);
			int32_t z0 = DepthKey(o0);                                    // [ebp-0x30]
			int32_t z1 = DepthKey(o1);                                    // [ebp-0x2C]
			int32_t z2 = DepthKey(o2);                                    // [ebp-0x28]
			uint8_t *p1 = vb + o1;
			uint8_t *p0 = vb + o0;
			uint8_t *p2 = vb + o2;
			uint32_t s0 = U32(p0, 0);
			uint32_t s2 = U32(p2, 0);
			uint32_t s1 = U32(p1, 0);
			U32(pkt, 0x10) = s1;
			U32(pkt, 8) = s0;
			U32(pkt, 0x18) = s2;
			if (nocull == 0)
			{
				int32_t mac0;
				x::GteWriteData((int32_t)s0, 12);
				x::GteWriteData((int32_t)s1, 13);
				x::GteWriteData((int32_t)s2, 14);
				x::GteNCLIP();
				x::GteReadData(&mac0, 24);
				if (mac0 < 0) goto next;
			}
			{
				uint32_t a0 = U32(p0, 4);
				uint32_t a1 = U32(p1, 4);
				uint32_t a2 = U32(p2, 4);
				if (((a2 | a1 | a0) >> 16) & 0x46) goto next;
				int32_t sum = (int32_t)((a2 + a1 + a0) & 0xFFFF);
				U8(pkt, 3) = 6;
				uint8_t *n;
				x::GteWriteData((int32_t)(U32(rec, 0) | U32(ws, 0x84)), 6);
				n = PTR(ws, 0x78) + U16(rec, 0xC);
				x::GteWriteData2(0, (int32_t)U32(n, 0));
				x::GteWriteData2(1, (int32_t)U32(n, 4));
				x::Gte_4601B0();
				x::GteReadData2(0x16, c0);
				x::GteWriteData((int32_t)(U32(rec, 4) | U32(ws, 0x84)), 6);
				n = PTR(ws, 0x78) + U16(rec, 0xC);
				x::GteWriteData2(0, (int32_t)U32(n, 0));
				x::GteWriteData2(1, (int32_t)U32(n, 4));
				x::Gte_4601B0();
				x::GteReadData2(0x16, c1);
				x::GteWriteData((int32_t)(U32(rec, 8) | U32(ws, 0x84)), 6);
				n = PTR(ws, 0x78) + U16(rec, 0xC);
				x::GteWriteData2(0, (int32_t)U32(n, 0));
				x::GteWriteData2(1, (int32_t)U32(n, 4));
				x::Gte_4601B0();
				x::GteReadData2(0x16, c2);
				uint32_t slot = ((uint32_t)Div3(sum) & 0x3FFC) + ot;
				x::InsertPrimDepthKeys(slot, pkt, z0, z1, z2, 0);
				c2 += 0x1C;
				pkt += 0x1C;
				c0 += 0x1C;
				c1 += 0x1C;
				U32(pkt, 0) = 0x2000000;
				U32(c0, 0) = U32(ws, 0x50);                               // = pkt + 4
				U32(pkt, 8) = 0;
				x::InsertPrimDepthKeys(slot, pkt, z0, z1, z2, 0);
				c1 += 0xC;
				pkt += 0xC;
				c2 += 0xC;
				c0 += 0xC;
			}
		next:
			rec += 0x14;
		} while (--count > 0);
		PTR(ws, 0x60) = pkt;
	}

	// ------------------------------------------------------------------------------------
	// 0xB62F70 (VM 0x04F OffscreenPass): cursor+2 s16 flags, +4 s16 w, +6 s16 h (-> ws+0xD4/
	// 0xD6). Skipped (cursor += 8) while RenderCtx+0x30 != 0. Builds an arena block at the arena
	// top: {+0 aux OT 0x1000 B (flags & 2) or 0, +4 OT 0x4000 B (flags & 1) or 0, +8 packet
	// buffer 0x5DC0 B, +0xC total size (also bone+0xC4, for VM 0x050 FreeArenaBlock), +0x14 arena
	// top after the allocation}; header 0xEC B (two DRAWENVs from +0x10). Then GTE = parent
	// transform (h_B27000), bone position projected to ws+0xD0 (screen x, y), ws+0xF0 = block,
	// and 0xB65810 renders the party models off-screen. Cursor += 8.
	// ------------------------------------------------------------------------------------
	static void __cdecl op_04F_OffscreenPass()
	{
		if (U16(RCTX(), 0x30) != 0)
		{
			STREAM() += 8;
			return;
		}
		U16(WS(), 0xD4) = U16(STREAM(), 4);
		U16(WS(), 0xD6) = U16(STREAM(), 6);
		uint8_t *blk = PTR(CTX(), 0x74);                                  // esi
		uint32_t size = 0xEC;                                             // eax
		FX_HELD(guard(blk, 0x10);)
		U32(blk, 0) = 0;
		U32(blk, 4) = 0;
		int32_t flags = S16(STREAM(), 2);                                 // ecx
		if (flags & 1)
		{
			uint32_t p = U32(CTX(), 0x74) + 0xEC;
			size = 0x40EC;
			U32(blk, 4) = p;
		}
		if (flags & 2)
		{
			uint32_t p = U32(CTX(), 0x74) + size;
			size += 0x1000;
			U32(blk, 0) = p;
		}
		{
			uint32_t p = U32(CTX(), 0x74) + size;
			size += 0x5DC0;
			U32(blk, 8) = p;
			U32(blk, 0xC) = size;
			U32(CUR(), 0xC4) = size;
		}
		blob::ArenaAlloc((int32_t)U32(blk, 0xC));
		U32(blk, 0x14) = U32(CTX(), 0x74);
		h_B27000();                                                       // 0xB5A150 (== Ifrit 0xB27000)
		{
			uint8_t *pos = WS() + 0xF0;
			U32(pos, 0) = U32(CUR(), 0x94);
			U16(pos, 4) = U16(CUR(), 0x98);
		}
		{
			uint8_t *w = WS();
			xl_RotTransPers(w + 0xF0, w + 0xD0, w + 0xFC, w + 0xFC);
		}
		PTR(WS(), 0xF0) = blk;
		xl_OffscreenRender_B65810();
		STREAM() += 8;
	}
}

	// installs the ports into a clone's tables (called after init_clone)
	void apply_lev_a(Clone &c)
	{
		c.draw[17] = part_lev_a::dh_17_RippleTextureUpload;   // 0xB59150
		c.draw[18] = part_lev_a::dh_18_WaterColumn;           // 0xB594B0 (+ 0xB5A150 = h_B27000)
		c.prim[2] = part_lev_a::pr_02_NormalLitG3;            // 0xB5C720
		c.vm[0x04F] = part_lev_a::op_04F_OffscreenPass;       // 0xB62F70 (+ 0xB5A150 = h_B27000)
	}
}
}

// ---- part lev_b
namespace ff8fx
{
namespace gfc
{
namespace part_lev_b
{
	// ------------------------------------------------------------------------------------
	// wrappers
	// ------------------------------------------------------------------------------------
	// 0x56CB30 (-> 0x56CB00): GTE SXY0/SXY1/SXY2 = a/b/c, GTE_NCLIP, returns MAC0 (0x1CA8A70).
	// Touches only the software GTE (no side effect outside the engine state).
	static int32_t xl_NormalClip_56CB30(int32_t a, int32_t b, int32_t c)
	{
		return x::f<int32_t (__cdecl *)(int32_t, int32_t, int32_t)>(0x56CB30)(a, b, c);
	}

	// ------------------------------------------------------------------------------------
	// 0xB5A760 MorphTableBuild: walks the geometry section ws+0xF0 (source mesh A) and, in step,
	// ws+0xF4 (target mesh B, same topology assumed: only B's per-object offsets are read, its
	// group headers are skipped), writing for every vertex a 12-byte record {A.x, A.y, A.z,
	// B.x*num/den, B.y*num/den, B.z*num/den} (num = ws+0xF8, den = ws+0xFC, 32-bit imul + idiv)
	// at the arena top (ctx+0x74) BEFORE allocating it, then ArenaAlloc(written size):
	// ws+0xFC = table, ws+0xF8 = size. Counters ws+0xD0 (objects, low word of the u32 count),
	// ws+0xD2 (object index), ws+0xD4 (groups left), all compared as s16.
	// Geometry section: u32 object count, u32 offsets[count] (from the section start); object:
	// u16 group count, groups {u16 bone, s16 vertex count, count x {s16 x, y, z}}.
	// ------------------------------------------------------------------------------------
	static void MorphTableBuild_B5A760()
	{
		uint8_t *out = PTR(CTX(), 0x74);                              // ecx
		uint8_t *w = WS();
		int32_t num = S32(w, 0xF8);                                   // [ebp-4]
		int32_t den = S32(w, 0xFC);                                   // ebx
		U16(w, 0xD0) = U16(PTR(w, 0xF0), 0);
		U16(WS(), 0xD2) = 0;
		w = WS();                                                     // edx
		if (S16(w, 0xD0) > S16(w, 0xD2))
		{
			do
			{
				int32_t i4 = shl32(S16(w, 0xD2), 2);
				uint8_t *ga = PTR(w, 0xF0);
				uint8_t *a = ga + U32(ga, i4 + 4);                    // esi
				a += 2;
				uint8_t *gb = PTR(w, 0xF4);
				uint8_t *b = gb + U32(gb, i4 + 4);                    // edi
				U16(w, 0xD4) = U16(a, -2);
				w = WS();
				b += 2;
				if (S16(w, 0xD4) > 0)
				{
					do
					{
						int32_t n = S16(a, 2);
						a += 4;
						b += 4;
						if (n > 0)
						{
							do
							{
								U16(out, 0) = U16(a, 0);
								a += 6;
								U16(out, 2) = U16(a, -4);
								U16(out, 4) = U16(a, -2);
								out += 0xC;
								S16(out, -6) = (int16_t)(mul32(S16(b, 0), num) / den);
								b += 6;
								S16(out, -4) = (int16_t)(mul32(S16(b, -4), num) / den);
								S16(out, -2) = (int16_t)(mul32(S16(b, -2), num) / den);
							} while (--n);
							w = WS();
						}
						U16(w, 0xD4) = (uint16_t)(U16(w, 0xD4) - 1);
						w = WS();
					} while (S16(w, 0xD4) > 0);
				}
				U16(w, 0xD2) = (uint16_t)(U16(w, 0xD2) + 1);
				w = WS();
			} while (S16(w, 0xD0) > S16(w, 0xD2));
		}
		int32_t size = (int32_t)((uint32_t)out - U32(CTX(), 0x74)); // esi
		uint8_t *t = blob::ArenaAlloc(size);
		PTR(WS(), 0xFC) = t;
		S32(WS(), 0xF8) = size;
	}

	// ------------------------------------------------------------------------------------
	// 0xB5A8E0 MorphApply: rewrites every vertex of the geometry section ws+0xF0 IN PLACE
	// (.00 file data) from the morph table ws+0xF8: v = A + ((B - A) * w) / 256 per axis
	// (32-bit imul, cdq/and 0xFF/add/sar 8 = division truncated toward zero), weights
	// w = ws+0xE0 / ws+0xE4 / ws+0xE8 (x / y / z). Same counters as 0xB5A760.
	// ------------------------------------------------------------------------------------
	static inline int32_t div256(int32_t v) { return add32(v, (v >> 31) & 0xFF) >> 8; }

	static void MorphApply_B5A8E0()
	{
		uint8_t *w = WS();                                            // eax
		int32_t wx = S32(w, 0xE0);                                    // [ebp-4]
		uint8_t *t = PTR(w, 0xF8);                                    // ecx
		int32_t wy = S32(w, 0xE4);                                    // [ebp-8]
		int32_t wz = S32(w, 0xE8);                                    // [ebp-0xc]
		U16(w, 0xD0) = U16(PTR(w, 0xF0), 0);
		U16(WS(), 0xD2) = 0;
		w = WS();
		int16_t si = S16(w, 0xD2);
		if (S16(w, 0xD0) > si)
		{
			do
			{
				uint8_t *g = PTR(w, 0xF0);
				uint8_t *v = g + U32(g, (int32_t)si * 4 + 4);         // esi
				U16(w, 0xD4) = U16(v, 0);
				v += 2;
				w = WS();
				if (S16(w, 0xD4) > 0)
				{
					do
					{
						int32_t n = S16(v, 2);                        // ebx
						v += 4;
						if (n > 0)
						{
							do
							{
								// 30 fps layer: see mag_leviathan_held.inc
								FX_HELD(held_note_vertex(v);)
								int32_t a = S16(t, 0);                // edi
								int32_t d = S16(t, 6) - a;
								v += 6;
								d = mul32(d, wx);
								t += 0xC;
								S16(v, -6) = (int16_t)add32(div256(d), a);
								a = S16(t, -0xA);
								d = mul32(S16(t, -4) - a, wy);
								S16(v, -4) = (int16_t)add32(div256(d), a);
								a = S16(t, -8);
								d = mul32(S16(t, -2) - a, wz);
								S16(v, -2) = (int16_t)add32(div256(d), a);
							} while (--n);
							w = WS();
						}
						U16(w, 0xD4) = (uint16_t)(U16(w, 0xD4) - 1);
						w = WS();
					} while (S16(w, 0xD4) > 0);
				}
				U16(w, 0xD2) = (uint16_t)(U16(w, 0xD2) + 1);
				w = WS();
				si = S16(w, 0xD2);
			} while (S16(w, 0xD0) > si);
		}
	}

	// ------------------------------------------------------------------------------------
	// 0xB5B010 ProjectVertexGroup(p, cursor): p = {u16 count, count x {s16 x, y, z}}.
	// ws+0xF0 = count (u16 zero-extended), ws+0xF4 = p + 2, ws+0xF8 = cursor. The FIRST vertex is
	// always projected (even when count == 0, vanilla quirk), then count - 1 more: GTE VXY0/VZ0,
	// RTPS, SXY2 -> record +0, SZ3 -> dword at record +0xC (i.e. the NEXT record's +4: record i
	// holds {SXY(i), SZ3(i-1)}, vanilla layout) and its low word into DEPTHARR[i] (0x2798C18,
	// scratch). Records are 8 bytes. ws+0xFC = end cursor, ws+0xF8 = end of the vertex data.
	// ------------------------------------------------------------------------------------
	static void ProjectVertexGroup_B5B010(uint8_t *p, uint32_t cursor)
	{
		U32(WS(), 0xF0) = U16(p, 0);
		PTR(WS(), 0xF4) = p + 2;
		U32(WS(), 0xF8) = cursor;
		uint8_t *w = WS();                                            // [ebp-8]
		int32_t cnt = S32(w, 0xF0);                                   // [ebp+0xc]
		uint8_t *v = PTR(w, 0xF4);                                    // esi
		uint8_t *o = PTR(w, 0xF8);                                    // edi
		int32_t tmp = (int32_t)(((uint32_t)U16(v, 2) << 16) | U16(v, 0)); // [ebp+8]
		int32_t z = U16(v, 4);                                        // ebx (upper half 0: xor at 0xB5B045)
		x::GteWriteData(tmp, 0);
		x::GteWriteData(z, 1);
		x::GteRTPS();
		int32_t left = cnt - 1;                                       // ebx
		v += 6;
		x::GteReadData2(0xE, o);
		x::GteReadData(&tmp, 0x13);
		o += 8;
		uint32_t *dp = DEPTHARR() + 1;                                // [ebp+0xc] = 0x2798C1C
		DEPTHARR()[0] = (uint32_t)tmp & 0xFFFF;
		S32(o, 4) = tmp;
		if (left > 0)
		{
			do
			{
				tmp = (int32_t)(((uint32_t)U16(v, 2) << 16) | U16(v, 0));
				z = U16(v, 4);
				x::GteWriteData(tmp, 0);
				x::GteWriteData(z, 1);
				x::GteRTPS();
				x::GteReadData2(0xE, o);
				v += 6;
				x::GteReadData(&tmp, 0x13);
				o += 8;
				*dp = (uint32_t)tmp & 0xFFFF;
				S32(o, 4) = tmp;
				dp++;
			} while (--left);
		}
		PTR(w, 0xFC) = o;
		PTR(w, 0xF8) = v;
	}

	// ------------------------------------------------------------------------------------
	// 0xB5B170 DrawScreenTexturedPrims: prims of the current object (block ws+0x84: +0x40 prim
	// data, +0x48 triangle count, +0x4A quad count) as PAIRS of packets per visible face
	// (NCLIP >= 0 on the pose-A projection ws+0x68):
	//   packet 1 (0x30 / 0x38 B): E2 texture window ws+0x88, 0, textured poly (FT3 0x24 /
	//     FT4 0x2C, colour ws+0x80 = bone2+0xCC), screen xy of pose A, UVs = low bytes of the
	//     screen x / y of pose B (ws+0x6C: the model projected with the second bone's transform),
	//     clut ws+0x7C (bone2+0x9A), tpage ws+0x78 (bone2+0x92), then E2000000 (window reset), 0;
	//   packet 2 (0x20 / 0x28 B): the face itself, code/colour ws+0xE8 (bone+0xCC & 0x2FFFFFF |
	//     0x24000000 / 0x2C000000), pose-A xy, the model's own UV / clut / tpage;
	// both inserted with InsertPrimDepthKeys at OT RT+0x4C + ((sum of z) / n >> 4) * 4 (tri: /3
	// via the 0x55555556 multiply, quad: /4), z = the +4 words of the pose-A vertex records.
	// Triangle record 0x10 B {u16 i0, i1, i2, uv2, uv0, clut, uv1, tpage}; quad record 0x14 B
	// {u16 i0, i1, i2, i3, clut +0xA?, ...: +6 -> +0xE, +8 uv0, +0xA -> +0x16, +0xC uv1,
	// +0x10 uv2, +0x12 uv3} (indices & 0xFFF, * 8 = vertex record offset).
	// Also: ws+0xF4 = ctx+0x7C, ws+0xFC = bone+0xDE, ws+0xE0 = RT+0x38 (dead stores, kept).
	// ctx+0x7C = new packet cursor. Returns 0 (unused).
	// ------------------------------------------------------------------------------------
	static void DrawScreenTexturedPrims_B5B170()
	{
		uint8_t *w = WS();                                            // ecx
		uint32_t pk0 = U32(CTX(), 0x7C);                              // edx
		uint8_t *b40 = PTR(w, 0x84) + 0x40;                           // eax
		U32(w, 0xF4) = pk0;
		U32(WS(), 0xFC) = U8(CUR(), 0xDE);
		U32(WS(), 0xE0) = U32(RT(), 0x38);
		U32(WS(), 0xE8) = (U32(CUR(), 0xCC) & 0x2FFFFFFu) | 0x24000000u;
		U16(WS(), 0xD0) = U16(b40, 8);
		U16(WS(), 0xD2) = U16(b40, 0xA);
		uint8_t *rec = PTR(b40, 0);                                   // ebx
		uint8_t *pk = PTR(CTX(), 0x7C);                               // esi
		w = WS();                                                     // eax
		int32_t ntri = S16(w, 0xD0);
		if (ntri > 0)
		{
			int32_t left = ntri;                                      // [ebp-0x20]
			do
			{
				uint32_t o2 = ((uint32_t)U16(rec, 4) & 0xFFF) << 3;  // [ebp-0xc]
				uint8_t *base = PTR(w, 0x68);                         // edi / [ebp-0x18]
				uint32_t o1 = ((uint32_t)U16(rec, 2) & 0xFFF) << 3;  // [ebp-8]
				uint32_t o0 = ((uint32_t)U16(rec, 0) & 0xFFF) << 3;  // [ebp-4]
				int32_t s2 = S32(base, o2);                           // [ebp-0x10]
				int32_t s1 = S32(base, o1);                           // [ebp-0x14]
				int32_t s0 = S32(base, o0);                           // [ebp-0x1c]
				if (xl_NormalClip_56CB30(s0, s1, s2) >= 0)
				{
					uint8_t *p2 = pk + 0x30;                          // edi
					U8(p2, 3) = 7;
					U32(pk, 8) = 0;
					U32(pk, 0x2C) = 0;
					U8(pk, 3) = 0xB;
					U32(pk, 0x28) = 0xE2000000u;
					S32(pk, 0x10) = s0;
					S32(p2, 8) = s0;
					S32(pk, 0x18) = s1;
					S32(p2, 0x10) = s1;
					S32(pk, 0x20) = s2;
					S32(p2, 0x18) = s2;
					int32_t z0 = S16(base, o0 + 4);                   // [ebp-0x14]
					int32_t z1 = S16(base, o1 + 4);                   // [ebp-0x10]
					int32_t z2 = S16(base, o2 + 4);                   // [ebp-0x1c]
					int32_t sum = z2 + z1 + z0;
					// imul 0x55555556 -> high dword, + its sign bit (= sum / 3), sar 4
					int32_t q = (int32_t)(((int64_t)sum * 0x55555556LL) >> 32);
					q += (int32_t)((uint32_t)q >> 31);
					q >>= 4;
					uint8_t *b2 = PTR(WS(), 0x6C);
					U8(pk, 0x14) = U8(b2 + o0, 0);
					U8(pk, 0x15) = U8(b2 + o0, 2);
					U8(pk, 0x1C) = U8(b2 + o1, 0);
					U8(pk, 0x1D) = U8(b2 + o1, 2);
					U8(pk, 0x24) = U8(b2 + o2, 0);
					U8(pk, 0x25) = U8(b2 + o2, 2);
					U16(p2, 0xC) = U16(rec, 8);
					U16(p2, 0x14) = U16(rec, 0xC);
					U16(p2, 0x1C) = U16(rec, 6);
					U16(p2, 0x16) = U16(rec, 0xE);
					U16(p2, 0xE) = U16(rec, 0xA);
					U32(p2, 4) = U32(WS(), 0xE8);
					U16(pk, 0x1E) = U16(WS(), 0x78);
					U16(pk, 0x16) = U16(WS(), 0x7C);
					U32(pk, 0xC) = U32(WS(), 0x80) | 0x24000000u;
					U32(pk, 4) = U32(WS(), 0x88);
					uint32_t d4 = (uint32_t)shl32(q, 2);              // [ebp-0x18]
					x::InsertPrimDepthKeys(U32(RT(), 0x4C) + d4, pk, z0, z1, z2, 0);
					x::InsertPrimDepthKeys(U32(RT(), 0x4C) + d4, p2, z0, z1, z2, 0);
					pk = p2 + 0x20;
				}
				rec += 0x10;
				w = WS();
			} while (--left);
		}
		U32(w, 0xE8) = (U32(w, 0xE8) & 0x2FFFFFFu) | 0x2C000000u;
		w = WS();
		int32_t nq = S16(w, 0xD2);
		if (nq <= 0)
		{
			PTR(CTX(), 0x7C) = pk;
			return;
		}
		rec += 4;                                                     // ebx = record + 4
		int32_t left = nq;                                            // [ebp-0x24]
		do
		{
			w = WS();
			uint32_t o2 = ((uint32_t)U16(rec, 0) & 0xFFF) << 3;      // [ebp-0xc]
			uint32_t o1 = ((uint32_t)U16(rec, -2) & 0xFFF) << 3;     // [ebp-8]
			uint8_t *base = PTR(w, 0x68);                             // edi / [ebp-0x18]
			uint32_t o0 = ((uint32_t)U16(rec, -4) & 0xFFF) << 3;     // [ebp-4]
			int32_t s2 = S32(base, o2);                               // [ebp-0x10]
			int32_t s1 = S32(base, o1);                               // [ebp-0x14]
			int32_t s0 = S32(base, o0);                               // [ebp-0x1c]
			if (xl_NormalClip_56CB30(s0, s1, s2) >= 0)
			{
				uint8_t *p2 = pk + 0x38;                              // edi
				U8(p2, 3) = 9;
				U32(pk, 8) = 0;
				U32(pk, 0x34) = 0;
				U8(pk, 3) = 0xD;
				U32(pk, 0x30) = 0xE2000000u;
				uint32_t o3 = ((uint32_t)U16(rec, 2) & 0xFFF) << 3;  // ecx
				int32_t s3 = S32(base, o3);                           // [ebp-0x20]
				S32(pk, 0x10) = s0;
				S32(p2, 8) = s0;
				S32(pk, 0x18) = s1;
				S32(p2, 0x10) = s1;
				S32(pk, 0x20) = s2;
				S32(p2, 0x18) = s2;
				S32(pk, 0x28) = s3;
				S32(p2, 0x20) = s3;
				int32_t z0 = S16(base, o0 + 4);                       // [ebp-0x14]
				int32_t z1 = S16(base, o1 + 4);                       // [ebp-0x10]
				int32_t z2 = S16(base, o2 + 4);                       // [ebp-0x1c]
				int32_t z3 = S16(base, o3 + 4);                       // [ebp-0x20]
				int32_t sum = z3 + z2 + z1 + z0;
				int32_t q = (sum + ((sum >> 31) & 3)) >> 2;           // cdq / and 3 / add / sar 2
				q >>= 4;                                              // [ebp-0x18]
				uint8_t *b2 = PTR(WS(), 0x6C);
				U8(pk, 0x14) = U8(b2 + o0, 0);
				U8(pk, 0x15) = U8(b2 + o0, 2);
				U8(pk, 0x1C) = U8(b2 + o1, 0);
				U8(pk, 0x1D) = U8(b2 + o1, 2);
				U8(pk, 0x24) = U8(b2 + o2, 0);
				U8(pk, 0x25) = U8(b2 + o2, 2);
				U8(pk, 0x2C) = U8(b2 + o3, 0);
				U8(pk, 0x2D) = U8(b2 + o3, 2);
				U16(p2, 0xC) = U16(rec, 4);
				U16(p2, 0x14) = U16(rec, 8);
				U16(p2, 0x1C) = U16(rec, 0xC);
				U16(p2, 0x24) = U16(rec, 0xE);
				U16(p2, 0x16) = U16(rec, 0xA);
				U16(p2, 0xE) = U16(rec, 6);
				U32(p2, 4) = U32(WS(), 0xE8);
				U16(pk, 0x1E) = U16(WS(), 0x78);
				U16(pk, 0x16) = U16(WS(), 0x7C);
				U32(pk, 0xC) = U32(WS(), 0x80) | 0x2C000000u;
				U32(pk, 4) = U32(WS(), 0x88);
				uint32_t d4 = (uint32_t)shl32(q, 2);
				x::InsertPrimDepthKeys(U32(RT(), 0x4C) + d4, pk, z0, z1, z2, z3);
				x::InsertPrimDepthKeys(U32(RT(), 0x4C) + d4, p2, z0, z1, z2, z3);
				pk = p2 + 0x28;
			}
			rec += 0x14;
		} while (--left);
		PTR(CTX(), 0x7C) = pk;
	}

	// ------------------------------------------------------------------------------------
	// bone matrices of the embedded model for the 0xB5AD50 renderer: BattleModel_
	// BuildBoneMatricesFromPose(blk+0x10).
	// ------------------------------------------------------------------------------------
	static void BuildPose(uint8_t *blk)
	{
		// 30 fps layer: see mag_leviathan_held.inc
		FX_HELD(if (held_mid24_pose(blk)) return;)
		x::BuildBoneMatricesFromPose(blk + 0x10);
	}

	// ------------------------------------------------------------------------------------
	// 0xB5AD50 DrawModelScreenTextured: model block ws+0xF0 (-> ws+0x84), second bone
	// GetBone(ws+0xF4) ("bone2"), alternative texture ReadAltTexture(ws+0xF8) -> ws+0x88 = GPU
	// texture-window command (E2) from the VRAM rect ws+0xF0 {x, y, w, h}; ws+0x78/0x7C/0x80 =
	// bone2 tpage (+0x92) / clut (+0x9A) / colour (+0xCC); ws+0x70/0x74 = bone +0x92/+0x9A;
	// ws+0x68 = arena top. Per object of the geometry section: (pass A) SetupParentXformScaled
	// of the current bone, bone matrices from pose, world matrices, every vertex group projected
	// with its bone's matrix into ws+0x68.. (0xB5B010); (pass B) the same with bone2's parent
	// transform (CUR() temporarily = bone2 around h_B269E0) into ws+0x6C.. (= end of pass A);
	// then the object's prim counts +0x48.. and prim data +0x40 (4-aligned after the groups)
	// and DrawScreenTexturedPrims. Returns 0 (unused).
	// ------------------------------------------------------------------------------------
	static void DrawModelScreenTextured_B5AD50()
	{
		U32(WS(), 0x84) = U32(WS(), 0xF0);
		uint8_t *w = WS();
		int32_t ref = S32(w, 0xF4);
		uint8_t *blk = PTR(w, 0x84);                                  // edi
		uint8_t *bone2 = blob::GetBone(ref);                          // esi / [ebp-0x18]
		blob::ReadAltTexture(S32(WS(), 0xF8));
		w = WS();                                                     // edx
		uint8_t *r = PTR(w, 0xF0);                                    // ecx
		int32_t e = shl32(S16(r, 2), 5) | S16(r, 0);
		// bx = r[2] over ebx = movsx r[0]: not / inc / sar 3 / and 0x1F -> bits 3..7 of -ebx
		uint32_t ebx = (S16(r, 0) < 0 ? 0xFFFF0000u : 0u) | U16(r, 4);
		uint32_t mx = (uint32_t)((int32_t)(~ebx + 1u) >> 3) & 0x1Fu;
		// cx = r[3] over the pointer's upper half: not / *4 + 4 / and 0x3E0 -> low bits only
		uint32_t ecx = ((uint32_t)r & 0xFFFF0000u) | U16(r, 6);
		uint32_t my = ((~ecx) * 4u + 4u) & 0x3E0u;
		e = shl32(e, 7);
		U32(w, 0x88) = my | ((uint32_t)e | mx) | 0xE2000000u;
		S32(WS(), 0x78) = S16(bone2, 0x92);
		S32(WS(), 0x7C) = S16(bone2, 0x9A);
		U32(WS(), 0x80) = U32(bone2, 0xCC);
		S32(WS(), 0x70) = S16(CUR(), 0x92);
		S32(WS(), 0x74) = S16(CUR(), 0x9A);
		U32(WS(), 0x68) = U32(CTX(), 0x74);
		uint8_t *bones = PTR(blk, 0x30) + 0x10;                       // [ebp-0xc]
		uint8_t *tab = PTR(blk, 0x34);                                // ebx
		int32_t nobj = S32(tab, 0);
		tab += 4;
		if (nobj <= 0) return;
		int32_t left = nobj;                                          // [ebp-0x14]
		do
		{
			// --- pass A: the model's own transform ---
			h_B269E0();
			BuildPose(blk);
			x::ComputeBonesWorldMatrices(blk + 0x10, WS() + 0xE0);
			uint8_t *obj = PTR(blk, 0x34) + U32(tab, 0);              // esi
			tab += 4;                                                 // [ebp-0x10]
			PTR(WS(), 0x8C) = obj;
			uint8_t *p = obj + 2;
			uint32_t cursor = U32(WS(), 0x68);                        // [ebp-4]
			int32_t ng = S16(p, -2);                                  // [ebp-8]
			if (ng > 0)
			{
				do
				{
					uint8_t *m = bones + S16(p, 0) * 0x30 + 0x10;     // ebx (lea *3, shl 4)
					x::SetRotMatrix(m);
					x::SetTransVector(m);
					p += 2;
					ProjectVertexGroup_B5B010(p, cursor);
					cursor = U32(WS(), 0xFC);
					p = PTR(WS(), 0xF8);
				} while (--ng);
			}
			// zero groups: ws+0xFC is whatever it held (ReadAltTexture's value or the previous
			// object's end cursor) - vanilla quirk kept
			U32(WS(), 0x6C) = U32(WS(), 0xFC);
			// --- pass B: bone2's parent transform ---
			uint8_t *save = CUR();
			CUR() = bone2;
			h_B269E0();
			CUR() = save;
			BuildPose(blk);
			x::ComputeBonesWorldMatrices(blk + 0x10, WS() + 0xE0);
			p = PTR(WS(), 0x8C);
			cursor = U32(WS(), 0x6C);
			ng = S16(p, 0);
			p += 2;
			if (ng > 0)
			{
				do
				{
					uint8_t *m = bones + S16(p, 0) * 0x30 + 0x10;
					x::SetRotMatrix(m);
					x::SetTransVector(m);
					p += 2;
					ProjectVertexGroup_B5B010(p, cursor);
					p = PTR(WS(), 0xF8);
					cursor = U32(WS(), 0xFC);
				} while (--ng);
			}
			// prim header after the vertex groups, 4-aligned: 4 u16 counts, 4 bytes, prim data
			uint8_t *q = (uint8_t *)(((uint32_t)p + 3) & ~3u);
			U16(blk, 0x48) = U16(q, 0);
			U16(blk, 0x4A) = U16(q, 2);
			U16(blk, 0x4C) = U16(q, 4);
			U16(blk, 0x4E) = U16(q, 6);
			PTR(blk, 0x40) = q + 0xC;
			DrawScreenTexturedPrims_B5B170();
		} while (--left);
	}

	// ------------------------------------------------------------------------------------
	// 0xB5A5B0 (Draw 20 MorphAnimModel): embedded battle model whose geometry is morphed toward
	// a second object's mesh. Parameters bone+0xB8 = {s16 model object, s16 morph target object,
	// s16 num, s16 den, s16 weight bone ref}. First draw (bone+0xBC == 0): block = h_B26860(obj),
	// morph table (0xB5A760) of the block's geometry (+0x34) vs the target object's section 2,
	// target scaled by num/den, block+4 = table. Every draw, gated ONLY by block flag bit0 (not
	// by boneSkipFlag): counter != 0 -> Battle_ReadAnimation, counter++, restart
	// (pre_Battle_ReadAnimation anim 0) when it returns 1 (vanilla: a counter of 0 is never
	// incremented here); flag bit0 re-read -> SetupParentXformScaled + world matrices. Then
	// block+0x44 = arena top, geometry morphed in place with weights = outPos (x, y, z) of the
	// weight bone (0xB5A8E0), RenderGeometry(block+0x30, block+0x40, RT+0x4C, 4, ctx+0x7C).
	// ------------------------------------------------------------------------------------
	static void __cdecl dh_20_MorphAnimModel()
	{
		uint8_t *cur = CUR();                                         // eax
		if (PTR(cur, 0xBC) == nullptr)
		{
			// 30 fps layer: see mag_leviathan_held.inc
			FX_HELD(if (held_active()) return;)
			uint8_t *prm = PTR(cur, 0xB8);                            // esi
			uint8_t *nb = h_B26860(S16(prm, 0));
			PTR(CUR(), 0xBC) = nb;
			uint8_t *blk = PTR(CUR(), 0xBC);                          // edi
			uint8_t *obj = blob::ObjectPtr(S16(prm, 2));
			PTR(WS(), 0xF4) = obj + U32(obj, 8);
			U32(WS(), 0xF0) = U32(blk, 0x34);
			S32(WS(), 0xF8) = S16(prm, 4);
			S32(WS(), 0xFC) = S16(prm, 6);
			MorphTableBuild_B5A760();
			U32(blk, 4) = U32(WS(), 0xFC);
			cur = CUR();
		}
		uint8_t *blk = PTR(cur, 0xBC);                                // esi
		uint8_t *hdr = blk + 0x10;                                    // edi
		uint8_t *cmd = blk + 0x20;                                    // ebx
		// 30 fps layer: see mag_leviathan_held.inc
		FX_HELD(if (held_active()) HeldBegin(blk);)
		if (!(U8(blk, 2) & 1))
		{
			if (U16(blk, 0) != 0)
			{
				// 30 fps layer: see mag_leviathan_held.inc
				FX_HELD(if (held_active()) held_pose20(hdr, cmd); else)
				{
					int32_t r = x::ReadAnimation(hdr, cmd);
					U16(blk, 0) = (uint16_t)(U16(blk, 0) + 1);
					if (r == 1) x::PreReadAnimation(hdr, cmd, 0);
				}
			}
			if (!(U8(blk, 2) & 1))
			{
				h_B269E0();
				x::ComputeBonesWorldMatrices(hdr, WS() + 0xE0);
			}
		}
		uint8_t *b40 = blk + 0x40;                                    // ebx
		uint8_t *b30 = blk + 0x30;                                    // edi
		U32(b40, 4) = U32(CTX(), 0x74);
		uint8_t *wb = blob::GetBone(S16(PTR(CUR(), 0xB8), 8));        // eax
		U32(WS(), 0xF0) = U32(b30, 4);
		U32(WS(), 0xF8) = U32(blk, 4);
		S32(WS(), 0xE0) = S16(wb, 0x94);
		S32(WS(), 0xE4) = S16(wb, 0x96);
		S32(WS(), 0xE8) = S16(wb, 0x98);
		MorphApply_B5A8E0();
		uint32_t cursor = U32(CTX(), 0x7C);
		uint32_t ot = U32(RT(), 0x4C);
		U32(CTX(), 0x7C) = x::RenderGeometry(b30, b40, ot, 4, cursor);
		// 30 fps layer: see mag_leviathan_held.inc
		FX_HELD(if (held_active()) HeldEnd();)
	}

	// ------------------------------------------------------------------------------------
	// 0xB5AB80 (Draw 24 AnimModelAltTex): embedded battle model drawn through the
	// screen-textured renderer 0xB5AD50. Parameters bone+0xB8 = {s16 model object, s16
	// alternative texture id, s16 bone2 ref}; optional morph parameters bone+0xC4 = {s16 morph
	// source object, s16 target object, s16 num, s16 den, s16 weight bone ref}. First draw
	// (bone+0xBC == 0): block = h_B26860, ReadAltTexture(id) -> bone+0xC0 = its VRAM rect
	// (ws+0xF0), and when bone+0xC4 != 0 the morph table source-vs-target (0xB5A760) ->
	// block+4. Every draw: when bone+0xC4 != 0 the source object's geometry is morphed with the
	// weight bone's outPos (0xB5A8E0); SetupParentXformScaled; h_B26AD0(block) (anim step, gated
	// by boneSkipFlag / flags); renderer (ws+0xF0 = block, ws+0xF4 = s16 bone+0xB8[+4],
	// ws+0xF8 = s16 bone+0xB8[+2]); then one extra unconditional counter++ (block+0).
	// ------------------------------------------------------------------------------------
	static void __cdecl dh_24_AnimModelAltTex()
	{
		uint8_t *cur = CUR();                                         // eax
		if (PTR(cur, 0xBC) == nullptr)
		{
			// 30 fps layer: see mag_leviathan_held.inc
			FX_HELD(if (held_active()) return;)
			uint8_t *prm = PTR(cur, 0xB8);                            // esi
			uint8_t *nb = h_B26860(S16(prm, 0));
			PTR(CUR(), 0xBC) = nb;
			blob::ReadAltTexture(S16(prm, 2));
			U32(CUR(), 0xC0) = U32(WS(), 0xF0);
			cur = CUR();
			uint8_t *mp = PTR(cur, 0xC4);                             // esi
			if (mp)
			{
				uint8_t *blk = PTR(cur, 0xBC);                        // edi
				uint8_t *o = blob::ObjectPtr(S16(mp, 2));
				PTR(WS(), 0xF4) = o + U32(o, 8);
				o = blob::ObjectPtr(S16(mp, 0));
				PTR(WS(), 0xF0) = o + U32(o, 8);
				S32(WS(), 0xF8) = S16(mp, 4);
				S32(WS(), 0xFC) = S16(mp, 6);
				MorphTableBuild_B5A760();
				U32(blk, 4) = U32(WS(), 0xFC);
				cur = CUR();
			}
		}
		// 30 fps layer: see mag_leviathan_held.inc
		FX_HELD(held_begin24(cur);)
		uint8_t *mp = PTR(cur, 0xC4);                                 // edi
		if (mp)
		{
			uint8_t *mb = PTR(cur, 0xBC);                             // ebx
			uint8_t *wb = blob::GetBone(S16(mp, 8));                  // esi
			uint8_t *o = blob::ObjectPtr(S16(mp, 0));
			PTR(WS(), 0xF0) = o + U32(o, 8);
			U32(WS(), 0xF8) = U32(mb, 4);
			S32(WS(), 0xE0) = S16(wb, 0x94);
			S32(WS(), 0xE4) = S16(wb, 0x96);
			S32(WS(), 0xE8) = S16(wb, 0x98);
			MorphApply_B5A8E0();
		}
		h_B269E0();
		h_B26AD0(PTR(CUR(), 0xBC));
		cur = CUR();
		uint8_t *blk = PTR(cur, 0xBC);                                // esi
		uint8_t *prm = PTR(cur, 0xB8);                                // eax
		PTR(WS(), 0xF0) = blk;
		S32(WS(), 0xF4) = S16(prm, 4);
		S32(WS(), 0xF8) = S16(prm, 2);
		DrawModelScreenTextured_B5AD50();
		// 30 fps layer: see mag_leviathan_held.inc
		FX_HELD(if (held_active()) held_end24(); else)
		U16(blk, 0) = (uint16_t)(U16(blk, 0) + 1);
	}
}

	// installs the ports into a clone's tables (called after init_clone)
	void apply_lev_b(Clone &c)
	{
		c.draw[20] = part_lev_b::dh_20_MorphAnimModel;
		c.draw[24] = part_lev_b::dh_24_AnimModelAltTex;
	}
}
}
// ==== END clone handler parts ====




namespace ff8fx
{
namespace gfc
{
namespace leviathan
{
	static Clone g_c = {};

	static void describe(Clone &c)
	{
		c.name = "006 Leviathan";
		c.effect_id = 6;
		c.vm_table = 0x1877864;
		c.bone_table = 0x18774D4;
		c.prim_table = 0x187751C;
		c.prim_size = 0x187760C;
		c.spr_table = 0x1877620;
		c.ptype_table = 0x187764C;
		c.pop_table = 0x1877660;
		c.draw_table = 0x18776C0;
		c.attr_16A = 0x187782A;
		c.attr_184 = 0x1877844;
		c.attr_186 = 0x1877846;
		c.attr_194 = 0x1877854;
		c.attr_19C = 0x187785C;
		c.desc = 0x187726C;
		c.ptr_block = 0x18774AC;
		c.queue = 0x2796EF8;
		c.file00 = 0x2796F0C;
		c.file01 = 0x2796F08;
		c.tick = 0xB586F0;
		c.load_cb = 0xB60530;
		c.lit_dispatcher = true;
		c.bone_count = 18;
	}

	static uint32_t __cdecl SequenceTask(TaskNode *)
	{
		return SequenceTick(g_c);
	}
}
}

	void register_gfc_leviathan()
	{
		using namespace gfc;
		leviathan::describe(leviathan::g_c);
		init_clone(leviathan::g_c, nullptr, 0);
		apply_lev_a(leviathan::g_c);
		apply_lev_b(leviathan::g_c);
		apply_shared_misc(leviathan::g_c);
		register_port(0xB586F0, (void *)leviathan::SequenceTask, "GFC006 Leviathan SequenceTick", 6);
		// 30 fps layer: see mag_leviathan_held.inc
		FX_HELD(register_gfc_leviathan_held();)
	}
}

#ifdef FF8_FX_HELD
#include "mag_leviathan_held.inc"
#endif
