/****************************************************************************/
//    Copyright (C) 2026 HobbitDur                                          //
//                                                                          //
//    This file is part of FFNx                                             //
//                                                                          //
//    FFNx is free software: you can redistribute it and/or modify          //
//    it under the terms of the GNU General Public License as published by  //
//    the Free Software Foundation, either version 3 of the License         //
//                                                                          //
//    FFNx is distributed in the hope that it will be useful,               //
//    but WITHOUT ANY WARRANTY; without even the implied warranty of        //
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         //
//    GNU General Public License for more details.                          //
/****************************************************************************/

// Effect 204: Alexander (cinematic-engine GF, module 0xAFFC80..0xB0C180, script data
// magic/MAG203_B.00/.01, streamed parts battle/mag203_b.02..). One clone of the GF cinematic
// engine (gfc_engine.cpp); this file holds the clone descriptor and the ports of the handlers that
// are not byte clones of the generic (Ifrit) ones.

#include "gfc_engine.h"

#ifdef FF8_FX_HELD
#include "mag_alexander_held.h"
#endif

// ==== BEGIN clone handler parts (generated by integrate.py) ====
// ---- part alexander
namespace ff8fx
{
namespace gfc
{
namespace part_alexander
{
	// ------------------------------------------------------------------------------------
	// local wrappers / constants (shared engine data, not module data)
	// ------------------------------------------------------------------------------------
	// dword_1D969C8: the battle's two DRAWENVs (PSX DRAWENV, 0x5C B = 23 dwords each), index =
	// (display parity - 1) & 1 = the one of the frame being built
	static const uint32_t BATTLE_DRAWENV_1D969C8 = 0x1D969C8;
	// byte_1D96A80: battle display buffer parity
	static inline uint8_t DISP_PARITY_1D96A80() { return MEM<uint8_t>(0x1D96A80); }

	// 0x45C0F0 SetDrawEnv(DR_ENV *p, const DRAWENV *env): builds the DR_ENV packet (tag length
	// 5, or 8 with isbg; writes p+0..p+0x23). Packet memory only.
	static inline void xl_SetDrawEnv_45C0F0(void *prim, const void *env) { x::f<void (__cdecl *)(void *, const void *)>(0x45C0F0)(prim, env); }
	// 0x45C7A0 SSIGPU_InsertPrimAutoDepth(ot slot address, prim): links prim into the OT slot
	// (OT node pool 0x1CA8828). Drawing only.
	static inline void xl_InsertPrimAutoDepth_45C7A0(uint32_t ot, void *prim) { x::f<void (__cdecl *)(uint32_t, void *)>(0x45C7A0)(ot, prim); }
	// 0xB65150 xorEAX_6: `xor eax, eax; ret` (called by 0xB02944, result unused). No effect; called at its address for call-trace parity.
	static inline void xl_Nop_B65150() { blob::f<int32_t (__cdecl *)()>(0xB65150)(); }
	// 0xB66840 (shared GF blob, not in blob::): ws+0xFC = colour ws+0xF0 scaled by ws+0xF4 / 256
	// per channel (r, g, b clamped to 0..255, the top byte of ws+0xF0 kept). Workspace only.
	static inline void xl_ScaleColour_B66840() { blob::f<int32_t (__cdecl *)()>(0xB66840)(); }

	// cdq; and edx, 0xFF; add eax, edx; sar eax, 8  (= v / 256 rounded toward zero)
	static inline int32_t div256(int32_t v) { return add32(v, (v >> 31) & 0xFF) >> 8; }
	// not eax; inc eax
	static inline int32_t neg32(int32_t v) { return (int32_t)(0u - (uint32_t)v); }

	// ------------------------------------------------------------------------------------
	// 0xB02540 (Draw 35 RenderToTexture): bone+0xB8 -> {s16 VRAM x, s16 VRAM y} of a 320x224
	// off-screen area. bone+0xBC -> 0x100 B block (arena, first call), two halves of 0x80 indexed
	// by the double-buffer flag rt+0x41 (pingPong), each holding two DR_ENV prims:
	//   +0x00 DR_ENV "draw into the off-screen area": a copy of the first 0x1C bytes of the
	//         current battle DRAWENV (dword_1D969C8[23 * ((byte_1D96A80 - 1) & 1)]) built at the
	//         arena top ctx+0x74 (scratch, not allocated), clip = ofs = (x, y), clip size
	//         0x140 x 0xE0, +0x18 = 0x1000000 (isbg 0, b0 1);
	//   +0x40 DR_ENV "back to the battle DRAWENV" (the current DRAWENV itself).
	// The +0x40 prim is linked at OT slot rt+0x4C + 0x10 and the +0x00 prim at rt+0x4C + 0x10 +
	// 4364 * 4, so every prim linked between those slots renders into the off-screen area.
	// Unless outAngleX (bone+0x8C) == 0x7654 (30292), the area is drawn back as five POLY_FT4
	// strips (0x28 B, code 0x2C | bone+0xCC, OT slot rt+0x4C + 8): strip i spans x = outPosX +
	// (outAngleX * i * 64 >> 8) .. (outAngleX * (i+1) * 64 >> 8), y = outPosY .. outPosY +
	// (outAngleY * 224 >> 8), UV (0,0)-(64,224), tpage ws+0x80 + i where ws+0x80 = ((x >> 2 & 0xF0
	// | y & 0x100) >> 4) | (s16)bone+0x92 | 0x100. ws+0x60/+0x64 = x/y, +0x68/+0x6C = outAngleX/Y.
	// Quirk kept: the strips' CLUT word (+0xE) and pad words are not written (stale packet
	// memory, vanilla); the parity read uses `mov cl` over a stale ecx (0xB02594) of which only
	// bit 0 survives the `dec; and 1`.
	// ------------------------------------------------------------------------------------
	static void __cdecl dh_35_RenderToTexture()
	{
		// 30 fps layer: see mag_alexander_held.inc
		FX_HELD(if (!held_active()))
		if (PTR(CUR(), 0xBC) == nullptr)
		{
			uint8_t *b = blob::ArenaAlloc(0x100);
			PTR(CUR(), 0xBC) = b;
		}
		uint8_t *prm = PTR(CUR(), 0xB8);
		S32(WS(), 0x60) = S16(prm, 0);
		S32(WS(), 0x64) = S16(prm, 2);
		uint32_t idx = ((uint32_t)DISP_PARITY_1D96A80() - 1u) & 1u;       // (cl - 1) & 1
		uint8_t *env = PTR(CTX(), 0x74);                                   // eax (arena top, scratch)
		const uint8_t *src = (const uint8_t *)(BATTLE_DRAWENV_1D969C8 + idx * 23u * 4u); // esi
		U32(env, 0) = U32(src, 0);
		U32(env, 4) = U32(src, 4);
		U32(env, 8) = U32(src, 8);
		U32(env, 0xC) = U32(src, 0xC);
		U32(env, 0x10) = U32(src, 0x10);
		U32(env, 0x14) = U32(src, 0x14);
		U32(env, 0x18) = U32(src, 0x18);
		uint8_t *prim;                                                     // edi
		// 30 fps layer: see mag_alexander_held.inc
		FX_HELD(if (held_active()) prim = held_env_prims(); else)
		prim = PTR(CUR(), 0xBC) + shl32(S8(RT(), 0x41), 7);
		uint16_t vx = U16(WS(), 0x60);
		U16(env, 8) = vx;
		U16(env, 0) = vx;
		uint16_t vy = U16(WS(), 0x64);
		U16(env, 0xA) = vy;
		U16(env, 2) = vy;
		U32(env, 4) = 0xE00140;
		U32(env, 0x18) = 0x1000000;
		xl_SetDrawEnv_45C0F0(prim, env);
		uint8_t *back = prim + 0x40;                                       // ebx
		xl_SetDrawEnv_45C0F0(back, src);
		uint32_t ot = U32(RT(), 0x4C) + 0x10;                              // esi
		xl_InsertPrimAutoDepth_45C7A0(ot, back);
		ot += 0x4430;
		xl_InsertPrimAutoDepth_45C7A0(ot, prim);

		uint8_t *ws = WS();
		int32_t tp = (S32(ws, 0x60) >> 2) & 0xF0;
		tp |= S32(ws, 0x64) & 0x100;
		tp >>= 4;
		tp |= S16(CUR(), 0x92);
		tp |= 0x100;                                                       // or ch, 1
		S32(ws, 0x80) = tp;
		uint8_t *pkt = PTR(CTX(), 0x7C);                                   // esi
		uint8_t *cur = CUR();
		int32_t x0 = S16(cur, 0x94);                                       // [ebp-4] / edx
		int32_t y0 = S16(cur, 0x96);                                       // edi
		S32(WS(), 0x68) = S16(cur, 0x8C);
		S32(WS(), 0x6C) = S16(CUR(), 0x8E);
		if (S32(WS(), 0x68) == 0x7654) return;
		int32_t i = 0;                                                     // eax
		do
		{
			U8(pkt, 3) = 9;
			int32_t n = i + 1;                                             // ebx
			U32(pkt, 4) = U32(CUR(), 0xCC) | 0x2C000000;
			U16(pkt, 0x16) = U16(WS(), 0x80);
			int32_t xa = add32(shl32(mul32(S32(WS(), 0x68), i), 6) >> 8, x0);
			U16(pkt, 0x18) = (uint16_t)xa;
			U16(pkt, 8) = (uint16_t)xa;
			int32_t w = S32(WS(), 0x68);
			U16(pkt, 0x12) = (uint16_t)y0;
			int32_t xb = shl32(mul32(w, n), 6) >> 8;
			U16(pkt, 0xA) = (uint16_t)y0;
			xb = add32(xb, x0);
			U16(pkt, 0x20) = (uint16_t)xb;
			U16(pkt, 0x10) = (uint16_t)xb;
			int32_t h = S32(WS(), 0x6C);
			U16(pkt, 0xC) = 0;
			U16(pkt, 0x14) = 0x40;
			U16(pkt, 0x1C) = 0xE000;
			int32_t yb = mul32(h, 8);
			U16(pkt, 0x24) = 0xE040;
			yb = sub32(yb, h);
			yb = shl32(yb, 5) >> 8;
			yb = add32(yb, y0);
			U16(pkt, 0x22) = (uint16_t)yb;
			U16(pkt, 0x1A) = (uint16_t)yb;
			xl_InsertPrimAutoDepth_45C7A0(U32(RT(), 0x4C) + 8, pkt);
			pkt += 0x28;
			U32(WS(), 0x80) = U32(WS(), 0x80) + 1;
			i = n;
		} while (i < 5);
		PTR(CTX(), 0x7C) = pkt;
	}

	// ------------------------------------------------------------------------------------
	// Draw 36 helpers (pieces of 0xB027F0 reached from several cases; e = vertex tables + 2*i:
	// +0/+2 X1[i]/X1[i+1] screen x offsets, +0x30/+0x32 Y1 screen y, +0x60/+0x62 X2 u offsets,
	// +0x90/+0x92 Y2 v offsets)
	// ------------------------------------------------------------------------------------
	static inline void Insert36(uint8_t *pkt) { xl_InsertPrimAutoDepth_45C7A0(U32(RT(), 0x4C) + 8, pkt); }

	// 0xB02A7A..0xB02AD5 (+ insert 0xB0340C): v bytes from ws+0x6C & 0xFF, screen x/y of the
	// full triangle
	static inline void Tail36_A(uint8_t *pkt, const uint8_t *e)
	{
		uint8_t v = (uint8_t)(U32(WS(), 0x6C) & 0xFF);
		U8(pkt, 0xD) = v;
		U8(pkt, 0x19) = (uint8_t)(U8(e, 0x90) + v);
		U8(pkt, 0x25) = (uint8_t)(U8(e, 0x92) + v);
		uint16_t x = U16(WS(), 0x68);
		U16(pkt, 8) = x;
		U16(pkt, 0x14) = (uint16_t)(U16(e, 0) + x);
		U16(pkt, 0x20) = (uint16_t)(x + U16(e, 2));
		uint16_t y = U16(WS(), 0x6C);
		U16(pkt, 0xA) = y;
		U16(pkt, 0x16) = (uint16_t)(U16(e, 0x30) + y);
		U16(pkt, 0x22) = (uint16_t)(U16(e, 0x32) + y);
		Insert36(pkt);
	}

	// 0xB02B97..0xB02BF3 == 0xB03002..0xB0305E: full GT3 head (code, black rim, screen x/y)
	static inline void FullTriHead36(uint8_t *pkt, const uint8_t *e)
	{
		U8(pkt, 3) = 9;
		uint32_t col = U32(WS(), 0x8C) | 0x34000000;
		U32(pkt, 0x1C) = 0;
		U32(pkt, 0x10) = 0;
		U32(pkt, 4) = col;
		uint16_t x = U16(WS(), 0x68);
		U16(pkt, 8) = x;
		U16(pkt, 0x14) = (uint16_t)(U16(e, 0) + x);
		U16(pkt, 0x20) = (uint16_t)(x + U16(e, 2));
		uint16_t y = U16(WS(), 0x6C);
		U16(pkt, 0xA) = y;
		U16(pkt, 0x16) = (uint16_t)(U16(e, 0x30) + y);
		U16(pkt, 0x22) = (uint16_t)(U16(e, 0x32) + y);
	}

	// 0xB02C08..0xB02C3C (+ insert 0xB0340C): u bytes from ub, v bytes from ws+0x94
	static inline void Tail36_UV(uint8_t *pkt, const uint8_t *e, uint8_t ub)
	{
		U8(pkt, 0xC) = ub;
		U8(pkt, 0x18) = (uint8_t)(U8(e, 0x60) + ub);
		U8(pkt, 0x24) = (uint8_t)(U8(e, 0x62) + ub);
		uint8_t v = (uint8_t)U32(WS(), 0x94);
		U8(pkt, 0xD) = v;
		U8(pkt, 0x19) = (uint8_t)(U8(e, 0x90) + v);
		U8(pkt, 0x25) = (uint8_t)(U8(e, 0x92) + v);
		Insert36(pkt);
	}

	// 0xB033ED..0xB03408 (+ insert 0xB0340C): centre u, screen x/y
	static inline void Tail36_B(uint8_t *pkt, uint8_t u)
	{
		U8(pkt, 0xC) = u;
		U16(pkt, 0xA) = U16(WS(), 0x6C);
		U16(pkt, 8) = U16(WS(), 0x68);
		Insert36(pkt);
	}

	// ------------------------------------------------------------------------------------
	// 0xB027F0 (Draw 36 ScreenLensDisc): a disc of 16 textured Gouraud segments around the
	// node's screen position that samples the off-screen screen copy of draw 35.
	// ws: +0x60/+0x64 = (s16) param x/y (VRAM position of the copy, bone+0xB8), +0x68/+0x6C =
	// outPosX/Y (screen centre), +0x70 = outAngleX (screen radius r1), +0x74 = outAngleY (UV
	// scale), +0x78 = r2 = r1 * scale >> 8 (UV radius), +0x80 = tpage of the centre column
	// (((x + px) >> 2 & 0xF0 | py & 0x100) >> 4 | (s16)bone+0x92 | 0x100), +0x84 = tpage of the
	// column left of the disc, +0x88 = u offset in that page, +0x8C = bone+0xCC & 0x2FFFFFF
	// (colour + semi-transparency), +0x90 = x & 0x3F (centre u), +0x94 = y & 0xFF (centre v),
	// +0xF0/+0xF4/+0xFC = colour / scale / result of 0xB66840.
	// Vertex tables at the arena top ctx+0x74 (scratch): 17 x {X1 = cos*r1 >> 12 (+0), Y1 =
	// sin*r1 >> 12 (+0x30), X2 = cos*r2 >> 12 (+0x60), Y2 = sin*r2 >> 12 (+0x90)}, angle 0..0x1000
	// step 0x100 (per angle, in this order: Cos, Sin, Cos, Sin).
	// Segment i (fan centre colour ws+0x8C, rim black), OT slot rt+0x4C + 8:
	//   0..3   POLY_GT3, tpage ws+0x80, u = centre u + X2
	//   4..7   POLY_GT3, tpage ws+0x84, u = ws+0x88 + x + X2
	//   8..11  tpage ws+0x84 (u base ws+0x88 + x), 12..15 tpage ws+0x80 (u base ws+0x90): the
	//          upper half may leave the texture page (v < 0): vA/vB = centre v + Y2[i]/Y2[i+1];
	//          (8..11: vB >= 0, 12..15: vA >= 0) -> full GT3; else the side still >= 0 gives a
	//          GT4 clipped at v = 0 (t = (v0 << 8) / (v0 - vOut) along centre->rim, t2 = (vIn
	//          << 8) / (vIn - vOut) along the rim edge; clipped centre-edge vertex coloured
	//          colour * (256 - t) / 256 by 0xB66840), and both < 0 gives a GT3 with both rim
	//          vertices clipped. Divisions: idiv (C '/'), products / 256: cdq/and/add/sar (div256).
	// Quirks kept: CLUT (+0xE) and pad words never written (stale packet memory, vanilla); the
	// segments 8..11 compute the clipped u / x / y with negated table values (neg, imul, div256,
	// subtract) and 12..15 with positive ones (imul, div256, add): the truncation differs by one
	// in places - reproduced as is. Writes only ws scratch, the arena-top scratch (ctx+0x74
	// onwards, not allocated) and packets.
	// ------------------------------------------------------------------------------------
	static void __cdecl dh_36_ScreenLensDisc()
	{
		uint8_t *prm = PTR(CUR(), 0xB8);
		S32(WS(), 0x60) = S16(prm, 0);
		S32(WS(), 0x64) = S16(prm, 2);
		S32(WS(), 0x68) = S16(CUR(), 0x94);
		S32(WS(), 0x6C) = S16(CUR(), 0x96);
		S32(WS(), 0x70) = S16(CUR(), 0x8C);
		S32(WS(), 0x74) = S16(CUR(), 0x8E);
		uint8_t *ws = WS();
		S32(ws, 0x78) = mul32(S32(ws, 0x74), S32(ws, 0x70)) >> 8;
		U32(WS(), 0x8C) = U32(CUR(), 0xCC) & 0x2FFFFFF;
		ws = WS();
		U32(ws, 0x90) = U32(ws, 0x68) & 0x3F;
		ws = WS();
		U32(ws, 0x94) = U32(ws, 0x6C) & 0xFF;
		ws = WS();
		{
			int32_t tp = (add32(S32(ws, 0x68), S32(ws, 0x60)) >> 2) & 0xF0;
			tp |= S32(ws, 0x64) & 0x100;
			tp >>= 4;
			tp |= S16(CUR(), 0x92);
			tp |= 0x100;                                                   // or ch, 1
			S32(ws, 0x80) = tp;
		}
		ws = WS();
		{
			int32_t a = add32(S32(ws, 0x68), S32(ws, 0x60));
			int32_t b = sub32(a, S32(ws, 0x78)) & 0xFFC0;
			a &= 0xFFC0;
			int32_t tp;
			if (a == b) tp = S32(ws, 0x80);
			else tp = sub32(S32(ws, 0x80), sub32(a, b) >> 6);
			S32(ws, 0x84) = tp;
		}
		xl_Nop_B65150();
		ws = WS();
		{
			int32_t d = sub32(S32(ws, 0x68), S32(ws, 0x78));
			uint32_t u = (uint32_t)d;
			if (d >= 0)
				u = 0u - (u & 0xFFC0);
			else
			{
				if ((u & 0x3F) == 0) u++;
				u = 0u - u;
				u &= 0xFFC0;
				u += 0x40;
			}
			U32(ws, 0x88) = u;
		}
		// vertex tables
		uint8_t *e = PTR(CTX(), 0x74);                                     // edi
		ws = WS();
		int32_t r1 = S32(ws, 0x70);                                        // [ebp-8]
		int32_t r2 = mul32(S32(ws, 0x74), r1) >> 8;                        // [ebp-0x10]
		for (int32_t ang = 0; ang <= 0x1000; ang += 0x100)
		{
			S16(e, 0) = (int16_t)(mul32(x::Cos(ang), r1) >> 12);
			S16(e, 0x30) = (int16_t)(mul32(x::Sin(ang), r1) >> 12);
			S16(e, 0x60) = (int16_t)(mul32(x::Cos(ang), r2) >> 12);
			S16(e, 0x90) = (int16_t)(mul32(x::Sin(ang), r2) >> 12);
			e += 2;
		}
		uint8_t *pkt = PTR(CTX(), 0x7C);                                   // esi
		e = PTR(CTX(), 0x74);
		ws = WS();
		U32(ws, 0xF0) = U32(ws, 0x8C);
		for (int32_t i = 0; i < 0x10; i++, e += 2)                         // [ebp-8]
		{
			if (i < 4)
			{
				U8(pkt, 3) = 9;
				uint32_t col = U32(WS(), 0x8C) | 0x34000000;
				U32(pkt, 0x1C) = 0;
				U32(pkt, 0x10) = 0;
				U32(pkt, 4) = col;
				U16(pkt, 0x1A) = U16(WS(), 0x80);
				uint8_t u = (uint8_t)(U32(WS(), 0x68) & 0x3F);
				U8(pkt, 0xC) = u;
				U8(pkt, 0x18) = (uint8_t)(U8(e, 0x60) + u);
				U8(pkt, 0x24) = (uint8_t)(U8(e, 0x62) + u);
				Tail36_A(pkt, e);
				pkt += 0x28;
			}
			else if (i < 8)
			{
				U8(pkt, 3) = 9;
				uint32_t col = U32(WS(), 0x8C) | 0x34000000;
				U32(pkt, 0x1C) = 0;
				U32(pkt, 0x10) = 0;
				U32(pkt, 4) = col;
				U16(pkt, 0x1A) = U16(WS(), 0x84);
				ws = WS();
				uint8_t xl = (uint8_t)U32(ws, 0x68);
				U8(pkt, 0xC) = (uint8_t)(U8(ws, 0x88) + xl);
				U8(pkt, 0x18) = (uint8_t)(U8(WS(), 0x88) + U8(e, 0x60) + xl);
				U8(pkt, 0x24) = (uint8_t)(U8(WS(), 0x88) + U8(e, 0x62) + xl);
				Tail36_A(pkt, e);
				pkt += 0x28;
			}
			else if (i < 12)
			{
				U16(pkt, 0x1A) = U16(WS(), 0x84);
				ws = WS();
				int32_t v0 = S32(ws, 0x94);                                // [ebp-0xC]
				int32_t vB = add32(S16(e, 0x92), v0);                      // ecx
				if (vB >= 0)
				{
					// 0xB02B97: full triangle
					FullTriHead36(pkt, e);
					ws = WS();
					Tail36_UV(pkt, e, (uint8_t)add32(S32(ws, 0x88), S32(ws, 0x68)));
					pkt += 0x28;
					continue;
				}
				int32_t vA = add32(S16(e, 0x90), v0);                      // [ebp-0x10]
				if (vA >= 0)
				{
					// 0xB02C56: rim B above the page -> GT4 clipped at v = 0
					U8(pkt, 3) = 0xC;
					uint32_t col = U32(WS(), 0x8C);
					U8(pkt, 0x25) = 0;
					col |= 0x3C000000;
					int32_t den = sub32(v0, vB);                           // ~vB + v0 + 1
					int32_t num = shl32(v0, 8);
					U32(pkt, 4) = col;
					int32_t t = num / den;                                 // ecx
					int32_t q = div256(mul32(S16(e, 0x62), t));
					ws = WS();
					U8(pkt, 0x24) = (uint8_t)((uint8_t)q + U8(ws, 0x88) + U8(ws, 0x68));
					q = div256(mul32(neg32(S16(e, 0x32)), t));
					U16(pkt, 0x22) = (uint16_t)(U16(WS(), 0x6C) - (uint16_t)q);
					q = div256(mul32(S16(e, 2), t));
					U16(pkt, 0x20) = (uint16_t)((uint16_t)q + U16(WS(), 0x68));
					S32(WS(), 0xF4) = sub32(0x100, t);
					xl_ScaleColour_B66840();
					U32(pkt, 0x1C) = U32(WS(), 0xFC);
					ws = WS();
					int32_t y2b = S16(e, 0x92);                            // edx
					int32_t v0b = S32(ws, 0x94);                           // eax
					int32_t vA2 = add32(S16(e, 0x90), v0b);                // ecx
					U8(pkt, 0x19) = (uint8_t)vA2;
					int32_t den2 = sub32(sub32(vA2, y2b), v0b);            // ebx
					int32_t t2 = shl32(vA2, 8) / den2;                     // [ebp-4]
					U8(pkt, 0x31) = 0;
					int32_t x2a = S16(e, 0x60);                            // [ebp-0x10]
					q = div256(mul32(sub32(S16(e, 0x62), x2a), t2));
					ws = WS();
					int32_t ua = add32(x2a, add32(S32(ws, 0x88), S32(ws, 0x68)));
					U8(pkt, 0x18) = (uint8_t)ua;
					U8(pkt, 0x30) = (uint8_t)((uint8_t)q + (uint8_t)ua);
					ws = WS();
					int32_t y1a = S16(e, 0x30);
					int32_t y1b = S16(e, 0x32);
					int32_t ya = add32(S32(ws, 0x6C), y1a);
					q = div256(mul32(sub32(y1a, y1b), t2));
					U16(pkt, 0x16) = (uint16_t)ya;
					U16(pkt, 0x2E) = (uint16_t)sub32(ya, q);
					int32_t x1a = S16(e, 0);
					q = div256(mul32(sub32(S16(e, 2), x1a), t2));
					int32_t xa = add32(x1a, S32(WS(), 0x68));
					U32(pkt, 0x28) = 0;
					U32(pkt, 0x10) = 0;
					U16(pkt, 0x14) = (uint16_t)xa;
					U16(pkt, 0x2C) = (uint16_t)add32(q, xa);
					U8(pkt, 0xD) = U8(WS(), 0x94);
					ws = WS();
					U8(pkt, 0xC) = (uint8_t)(U8(ws, 0x88) + U8(ws, 0x68));
					U16(pkt, 0xA) = U16(WS(), 0x6C);
					U16(pkt, 8) = U16(WS(), 0x68);
					Insert36(pkt);
					pkt += 0x34;
				}
				else
				{
					// 0xB02E2A: both rim vertices above the page -> GT3, both clipped
					U8(pkt, 3) = 9;
					uint32_t col = U32(WS(), 0x8C);
					U8(pkt, 0x25) = 0;
					col |= 0x34000000;
					int32_t den = sub32(v0, vB);
					U32(pkt, 4) = col;
					int32_t num = shl32(v0, 8);                            // [ebp-4]
					int32_t t = num / den;
					int32_t q = div256(mul32(neg32(S16(e, 0x62)), t));
					uint8_t b = (uint8_t)(U8(WS(), 0x88) - (uint8_t)q);
					b = (uint8_t)(b + U8(WS(), 0x68));
					U8(pkt, 0x24) = b;
					q = div256(mul32(neg32(S16(e, 0x32)), t));
					U16(pkt, 0x22) = (uint16_t)(U16(WS(), 0x6C) - (uint16_t)q);
					q = div256(mul32(neg32(S16(e, 2)), t));
					U16(pkt, 0x20) = (uint16_t)(U16(WS(), 0x68) - (uint16_t)q);
					S32(WS(), 0xF4) = sub32(0x100, t);
					xl_ScaleColour_B66840();
					uint32_t c2 = U32(WS(), 0xFC);
					U8(pkt, 0x19) = 0;
					U32(pkt, 0x1C) = c2;
					den = sub32(v0, vA);
					t = num / den;
					q = div256(mul32(neg32(S16(e, 0x60)), t));
					b = (uint8_t)(U8(WS(), 0x88) - (uint8_t)q);
					b = (uint8_t)(b + U8(WS(), 0x68));
					U8(pkt, 0x18) = b;
					q = div256(mul32(neg32(S16(e, 0x30)), t));
					U16(pkt, 0x16) = (uint16_t)(U16(WS(), 0x6C) - (uint16_t)q);
					q = div256(mul32(neg32(S16(e, 0)), t));
					U16(pkt, 0x14) = (uint16_t)(U16(WS(), 0x68) - (uint16_t)q);
					S32(WS(), 0xF4) = sub32(0x100, t);
					xl_ScaleColour_B66840();
					U32(pkt, 0x10) = U32(WS(), 0xFC);
					U8(pkt, 0xD) = U8(WS(), 0x94);
					ws = WS();
					Tail36_B(pkt, (uint8_t)(U8(ws, 0x88) + U8(ws, 0x68)));
					pkt += 0x28;
				}
			}
			else
			{
				U16(pkt, 0x1A) = U16(WS(), 0x80);
				ws = WS();
				int32_t v0 = S32(ws, 0x94);                                // [ebp-0xC]
				int32_t vA = add32(S16(e, 0x90), v0);                      // ecx
				if (vA >= 0)
				{
					// 0xB03002: full triangle
					FullTriHead36(pkt, e);
					Tail36_UV(pkt, e, (uint8_t)U32(WS(), 0x90));
					pkt += 0x28;
					continue;
				}
				int32_t vB = add32(S16(e, 0x92), v0);                      // [ebp-0x10]
				if (vB >= 0)
				{
					// 0xB03084: rim A above the page -> GT4 clipped at v = 0
					U8(pkt, 3) = 0xC;
					uint32_t col = U32(WS(), 0x8C);
					U8(pkt, 0x19) = 0;
					col |= 0x3C000000;
					int32_t den = sub32(v0, vA);
					int32_t num = shl32(v0, 8);
					U32(pkt, 4) = col;
					int32_t t = num / den;                                 // ecx
					int32_t q = div256(mul32(S16(e, 0x60), t));
					U8(pkt, 0x18) = (uint8_t)((uint8_t)q + U8(WS(), 0x90));
					q = div256(mul32(neg32(S16(e, 0x30)), t));
					U16(pkt, 0x16) = (uint16_t)(U16(WS(), 0x6C) - (uint16_t)q);
					q = div256(mul32(S16(e, 0), t));
					U16(pkt, 0x14) = (uint16_t)((uint16_t)q + U16(WS(), 0x68));
					S32(WS(), 0xF4) = sub32(0x100, t);
					xl_ScaleColour_B66840();
					U32(pkt, 0x10) = U32(WS(), 0xFC);
					ws = WS();
					int32_t y2b = S16(e, 0x92);                            // eax
					int32_t v0b = S32(ws, 0x94);                           // ecx / [ebp-0x10]
					int32_t y2a = S16(e, 0x90);                            // edx
					int32_t vB2 = add32(y2b, v0b);                         // [ebp-0xC]
					int32_t den2 = sub32(sub32(vB2, y2a), v0b);
					U8(pkt, 0x31) = 0;
					int32_t t2 = shl32(vB2, 8) / den2;                     // [ebp-4]
					U8(pkt, 0x25) = (uint8_t)vB2;
					ws = WS();
					int32_t x2a = S16(e, 0x60);
					int32_t ub = add32(S32(ws, 0x90), S16(e, 0x62));
					q = div256(mul32(sub32(S16(e, 0x62), x2a), t2));
					U8(pkt, 0x30) = (uint8_t)((uint8_t)ub - (uint8_t)q);
					U8(pkt, 0x24) = (uint8_t)ub;
					ws = WS();
					int32_t y1b = S16(e, 0x32);
					int32_t y1a = S16(e, 0x30);
					int32_t yb = add32(S32(ws, 0x6C), y1b);
					q = div256(mul32(sub32(y1b, y1a), t2));
					U16(pkt, 0x22) = (uint16_t)yb;
					U16(pkt, 0x2E) = (uint16_t)sub32(yb, q);
					ws = WS();
					int32_t x1b = S16(e, 2);
					int32_t x1a = S16(e, 0);
					int32_t xb = add32(S32(ws, 0x68), x1b);
					U32(pkt, 0x28) = 0;
					q = div256(mul32(sub32(x1b, x1a), t2));
					U16(pkt, 0x20) = (uint16_t)xb;
					U32(pkt, 0x1C) = 0;
					U16(pkt, 0x2C) = (uint16_t)sub32(xb, q);
					U8(pkt, 0xD) = U8(WS(), 0x94);
					U8(pkt, 0xC) = U8(WS(), 0x90);
					U16(pkt, 0xA) = U16(WS(), 0x6C);
					U16(pkt, 8) = U16(WS(), 0x68);
					Insert36(pkt);
					pkt += 0x34;
				}
				else
				{
					// 0xB0326A: both rim vertices above the page -> GT3, both clipped
					U8(pkt, 3) = 9;
					uint32_t col = U32(WS(), 0x8C);
					U8(pkt, 0x19) = 0;
					col |= 0x34000000;
					int32_t den = sub32(v0, vA);
					U32(pkt, 4) = col;
					int32_t num = shl32(v0, 8);                            // [ebp-4]
					int32_t t = num / den;
					int32_t q = div256(mul32(S16(e, 0x60), t));
					U8(pkt, 0x18) = (uint8_t)((uint8_t)q + U8(WS(), 0x90));
					q = div256(mul32(neg32(S16(e, 0x30)), t));
					U16(pkt, 0x16) = (uint16_t)(U16(WS(), 0x6C) - (uint16_t)q);
					q = div256(mul32(S16(e, 0), t));
					U16(pkt, 0x14) = (uint16_t)((uint16_t)q + U16(WS(), 0x68));
					S32(WS(), 0xF4) = sub32(0x100, t);
					xl_ScaleColour_B66840();
					uint32_t c1 = U32(WS(), 0xFC);
					U8(pkt, 0x25) = 0;
					U32(pkt, 0x10) = c1;
					den = sub32(v0, vB);
					t = num / den;
					q = div256(mul32(S16(e, 0x62), t));
					U8(pkt, 0x24) = (uint8_t)((uint8_t)q + U8(WS(), 0x90));
					q = div256(mul32(neg32(S16(e, 0x32)), t));
					U16(pkt, 0x22) = (uint16_t)(U16(WS(), 0x6C) - (uint16_t)q);
					q = div256(mul32(S16(e, 2), t));
					U16(pkt, 0x20) = (uint16_t)((uint16_t)q + U16(WS(), 0x68));
					S32(WS(), 0xF4) = sub32(0x100, t);
					xl_ScaleColour_B66840();
					U32(pkt, 0x1C) = U32(WS(), 0xFC);
					U8(pkt, 0xD) = U8(WS(), 0x94);
					Tail36_B(pkt, U8(WS(), 0x90));
					pkt += 0x28;
				}
			}
		}
		PTR(CTX(), 0x7C) = pkt;
	}
}
	// installs the ports into a clone's tables (called after init_clone)
	void apply_alexander(Clone &c)
	{
		c.draw[35] = part_alexander::dh_35_RenderToTexture;   // 0xB02540
		c.draw[36] = part_alexander::dh_36_ScreenLensDisc;    // 0xB027F0
	}
}
}
// ==== END clone handler parts ====




namespace ff8fx
{
namespace gfc
{
namespace alexander
{
	static Clone g_c = {};

	static void describe(Clone &c)
	{
		c.name = "204 Alexander";
		c.effect_id = 204;
		c.vm_table = 0x18729C0;
		c.bone_table = 0x1872630;
		c.prim_table = 0x1872678;
		c.prim_size = 0x1872768;
		c.spr_table = 0x187277C;
		c.ptype_table = 0x18727A8;
		c.pop_table = 0x18727BC;
		c.draw_table = 0x187281C;
		c.attr_16A = 0x1872986;
		c.attr_184 = 0x18729A0;
		c.attr_186 = 0x18729A2;
		c.attr_194 = 0x18729B0;
		c.attr_19C = 0x18729B8;
		c.desc = 0x1872384;
		c.ptr_block = 0x1872608;
		c.queue = 0x2796D70;
		c.file00 = 0x2796DA4;
		c.file01 = 0x2796DA0;
		c.tick = 0xB00310;
		c.load_cb = 0xB07C20;
		c.lit_dispatcher = false;
		c.bone_count = 18;
	}

	static uint32_t __cdecl SequenceTask(TaskNode *)
	{
		return SequenceTick(g_c);
	}
}
}

	void register_gfc_alexander()
	{
		using namespace gfc;
		alexander::describe(alexander::g_c);
		init_clone(alexander::g_c, nullptr, 0);
		apply_alexander(alexander::g_c);
		apply_shared_ribbon(alexander::g_c);
		apply_shared_misc(alexander::g_c);
		register_port(0xB00310, (void *)alexander::SequenceTask, "GFC204 Alexander SequenceTick", 204);
		// 30 fps layer: see mag_alexander_held.inc
		FX_HELD(register_gfc_alexander_held();)
	}
}

#ifdef FF8_FX_HELD
#include "mag_alexander_held.inc"
#endif
