/****************************************************************************/
//    Copyright (C) 2026 HobbitDur                                          //
//                                                                          //
//    This file is part of FFNx                                             //
//                                                                          //
//    FFNx is free software: you can redistribute it and/or modify          //
//    it under the terms of the GNU General Public License as published by  //
//    the Free Software Foundation, either version 3 of the License         //
//                                                                          //
//    FFNx is distributed in the hope that it will be useful,               //
//    but WITHOUT ANY WARRANTY; without even the implied warranty of        //
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         //
//    GNU General Public License for more details.                          //
/****************************************************************************/

// Effect 205: Brothers (cinematic-engine GF, module 0xAF4500..0xAFFC80, script data
// magic/MAG204_B.00/.01, streamed parts battle/mag204_b.02..). One clone of the GF cinematic
// engine (gfc_engine.cpp); this file holds the clone descriptor and the ports of the handlers that
// are not byte clones of the generic (Ifrit) ones.

#include "gfc_engine.h"

// ==== BEGIN clone handler parts (generated by integrate.py) ====
// ---- part brothers
namespace ff8fx
{
namespace gfc
{
namespace part_brothers
{
	// ------------------------------------------------------------------------------------
	// constants (addresses outside the module data window)
	// ------------------------------------------------------------------------------------
	// Brothers module static byte (outside the engine snapshot block 0x2796E00..): "Norg room
	// target fix-up active" flag of VM 0x0D5
	static const uint32_t BROTHERS_FLAG_2796D40 = 0x2796D40;
	// shared battle globals
	static const uint32_t COMBAT_SCENE_ID_1CFF6E0 = 0x1CFF6E0;       // u16 current battle stage id
	static const uint32_t MODEL_SLOT0_FILEID_1D98990 = 0x1D98990;    // stru_1D9898C[0].battle_file_id (u8)
	static const uint32_t DWORD_1D98A4C = 0x1D98A4C;                 // low byte = colour level (VM 0x0DA bit12)
	static const uint32_t WORD_1D974B0 = 0x1D974B0;                  // 3 x s16 position copied by VM 0x0D5
	static const uint32_t WORD_1D97494 = 0x1D97494;                  // battle struct, address stored in SceneHeader+0x6C
	// engine block: 8 zero dwords (cleared by SetupSectionPtrs), used as a null translation
	static inline uint8_t *ZEROVEC() { return (uint8_t *)0x27971E4; }

	// ------------------------------------------------------------------------------------
	// engine / blob wrappers (original addresses)
	// ------------------------------------------------------------------------------------
	// 0x56CE30 ComposeZYXRotationMatrix(angles 3 x s16, out): out = identity, then Z, X, Y rotations
	static inline void *xl_ComposeZYXRotation(const void *angles, void *out) { return x::f<void *(__cdecl *)(const void *, void *)>(0x56CE30)(angles, out); }
	// 0x56C3D0 apply3DTransform(m, v 3 x s16, out 3 x s32): out = m.rot * v (float, rounded)
	static inline void xl_Apply3DTransform(const void *m, const void *v, void *out) { x::f<void (__cdecl *)(const void *, const void *, void *)>(0x56C3D0)(m, v, out); }
	// 0x56C850 (RotTrans to IR): GTE_LoadV0(v); MVMVA R*V0+TR; IR1..3 -> ir (3 x s16); FLAG -> *flag
	static inline void xl_RotTransIR(const void *v, void *ir, void *flag) { x::f<void (__cdecl *)(const void *, void *, void *)>(0x56C850)(v, ir, flag); }
	// 0x56C880 TransformWorldCoordinateToProjectedSpace(v, sxy, p, flag): RTPS; SXY2 -> sxy (4 bytes),
	// interpolation value -> *p, FLAG -> *flag; returns OTZ
	static inline int32_t xl_RotTransPers(const void *v, void *sxy, void *p, void *flag) { return x::f<int32_t (__cdecl *)(const void *, void *, void *, void *)>(0x56C880)(v, sxy, p, flag); }
	// 0x56CB30 (NormalClip): SXY0..2 = a, b, c; GTE NCLIP; returns MAC0
	static inline int32_t xl_NormalClip(int32_t a, int32_t b, int32_t c) { return x::f<int32_t (__cdecl *)(int32_t, int32_t, int32_t)>(0x56CB30)(a, b, c); }
	// 0xB67040 (blob) model shadow: root != 0 -> BuildBoneMatricesFromPose(hdr) +
	// ComputeBonesWorldMatrices(hdr, root); ellipse (8 flat semi-transparent triangles, code
	// 0x32, grey level `level`) of the skeleton's XZ extent at height y, projected; OT = -1 ->
	// FRAMERL+0x4064 else RT+0x4C + (ot & 0x3FFC); packets at ctx+0x7C; root != 0 ->
	// BuildBoneMatricesFromPose(hdr) again. Writes the model skeleton, ws, GTE, packets/OT only.
	static inline void xl_ModelShadow_B67040(void *hdr, void *root, int32_t ot, int32_t y, int32_t level)
	{
		x::f<int32_t (__cdecl *)(void *, void *, int32_t, int32_t, int32_t)>(0xB67040)(hdr, root, ot, y, level);
	}
	// 0xB65F30 (blob) off-screen render of battle model slot 1 (stru_1D9898C[1]) at pos/angles into
	// the VRAM rect of ws+0xD0.. through its own OT, executed at once (SSIGPU_ExecuteOrderingTable).
	// External side effect: does nothing while predicting.
	static inline void xl_OffscreenModelRender_B65F30(void *desc, const void *pos, const void *angles)
	{
		if (!g_predict) x::f<int32_t (__cdecl *)(void *, const void *, const void *)>(0xB65F30)(desc, pos, angles);
	}

	// ------------------------------------------------------------------------------------
	// held frames: battle entity bytes + skeleton written by draw handlers 38 / 48 (outside
	// every saved set) are saved before the held draw of the handler and put back after it
	// ------------------------------------------------------------------------------------
	struct EntityHeldSave
	{
		uint8_t *ent;
		uint32_t head_n;
		uint8_t head[0x24];
		uint8_t *sk;
		uint32_t sk_n;
	};
	static uint8_t g_held_skel[0x10 + 0x30 * 256];

	// head_n bytes of the entity + its skeleton (*(*(ent+0x64)), 0x10 + 0x30 * bone count bytes: the
	// region BuildBoneMatricesFromPose / ComputeBonesWorldMatrices write, as HeldFrame's model saves)
	static void held_save_entity(EntityHeldSave &s, uint8_t *ent, uint32_t head_n)
	{
		s.ent = ent;
		s.head_n = head_n;
		memcpy(s.head, ent, head_n);
		uint8_t *p = PTR(ent, 0x64);
		s.sk = p ? PTR(p, 0) : nullptr;
		s.sk_n = s.sk ? 0x10 + 0x30 * (uint32_t)U8(s.sk, 0) : 0;
		if (s.sk) memcpy(g_held_skel, s.sk, s.sk_n);
	}

	static void held_restore_entity(const EntityHeldSave &s)
	{
		memcpy(s.ent, s.head, s.head_n);
		if (s.sk) memcpy(s.sk, g_held_skel, s.sk_n);
	}

	// ------------------------------------------------------------------------------------
	// 0xAF5810 (Draw 3 AnimatedModelWithShadow): generic draw 3 (0xAF5670 == Ifrit 0xB269E0
	// SetupParentXformScaled, 0xAF5760 == Ifrit 0xB26AD0 StepEmbeddedModelAnim, RenderGeometry
	// mode 4, block+0x44 = arena scratch), then, when the model block flag byte +2 has bit 2: the
	// model's projected shadow through blob 0xB67040 with root matrix ws+0x80 = rotation of the
	// parent node (bone+0x9C) in order 0 scaled by 16*bone scale (+0x8C/8E/90), translation =
	// parent outPos; OT spec / plane height = the two s16 at *(block+0x7C); grey level 0x80.
	// Held frames: the embedded model is posed as in h_B26AD0 (pose_midpoint when the real tick
	// advanced it). The shadow: when the model was advanced (same test as h_B26AD0's in-between
	// path) the bone matrices are built from the in-between pose (pose_midpoint) + world matrices
	// from ws+0x80 and 0xB67040 is called with root = 0 (it then neither rebuilds from the real
	// pose nor rebuilds after), so the shadow follows the in-between model; otherwise the vanilla
	// call. The skeleton writes are undone by HeldFrame (draw 3 model blocks are saved).
	// ------------------------------------------------------------------------------------
	static void __cdecl dh_03_AnimatedModelWithShadow()
	{
		h_B269E0();
		bool mid = false;
		if (g_held.active)
		{
			// h_B26AD0's in-between test (rt+0x45 is forced, its frozen path runs), before it runs
			uint8_t *b = PTR(CUR(), 0xBC);
			uint16_t fl = U16(b, 2);
			mid = g_held.real_skip == 0 && !(fl & 1) && U16(b, 0) != 0 && !(fl & 2);
		}
		h_B26AD0(PTR(CUR(), 0xBC));
		uint8_t *blk = PTR(CUR(), 0xBC);                                  // esi
		U32(blk, 0x44) = U32(CTX(), 0x74);
		uint32_t cursor = U32(CTX(), 0x7C);
		uint32_t ot = U32(RT(), 0x4C);
		U32(CTX(), 0x7C) = x::RenderGeometry(blk + 0x30, blk + 0x40, ot, 4, cursor);
		if (!(U8(blk, 2) & 4)) return;
		uint8_t *par = blob::GetBone((int32_t)U16(CUR(), 0x9C));         // edi
		blob::RotMatrixOrder(par + 0x8C, 0);                              // -> ws+0xE0
		blob::CopyMatrix(WS() + 0x80, WS() + 0xE0);
		S32(WS(), 0x60) = shl32(S16(CUR(), 0x8C), 4);
		S32(WS(), 0x64) = shl32(S16(CUR(), 0x8E), 4);
		S32(WS(), 0x68) = shl32(S16(CUR(), 0x90), 4);
		x::ScaleMatrix(WS() + 0x80, WS() + 0x60);
		uint8_t *hdr = blk + 0x10;                                        // esi += 0x10
		S32(WS(), 0x94) = S16(par, 0x94);
		S32(WS(), 0x98) = S16(par, 0x96);
		S32(WS(), 0x9C) = S16(par, 0x98);
		uint8_t *sp = PTR(hdr, 0x6C);                                     // block+0x7C
		int32_t y = S16(sp, 2);
		int32_t otspec = S16(sp, 0);
		if (mid)
		{
			pose_midpoint(hdr, blk + 0x20, g_held.num, g_held.den);
			x::ComputeBonesWorldMatrices(hdr, WS() + 0x80);
			xl_ModelShadow_B67040(hdr, nullptr, otspec, y, 0x80);
		}
		else
			xl_ModelShadow_B67040(hdr, WS() + 0x80, otspec, y, 0x80);
	}

	// ------------------------------------------------------------------------------------
	// 0xAF5D00 EntityShadow(ent, root, pos, 0x1000 unused): shadow of a live battle entity.
	// ent[0] |= 0x20; its bone matrices from its pose + world matrices from root; XZ extent of
	// the bone ends (bone 0 translation +-500 start, bones 1..n-1 through RotTrans of (0,0,len));
	// centre = pos + (mid x, 0, mid z) projected through node 0 (camera) -> GTE TR; ellipse of 8
	// flat semi-transparent triangles (code = ent+0x2C) through RTPS, drawn when the fan faces
	// the camera (NCLIP > 0), OT FRAMERL+0x4064 with depth keys 0; bone matrices rebuilt after.
	// ------------------------------------------------------------------------------------
	static void EntityShadow_AF5D00(uint8_t *ent, uint8_t *root, uint8_t *pos)
	{
		uint8_t *w = WS();                                                // esi
		U8(ent, 0) |= 0x20;
		uint8_t *hdr = ent + 0x60;                                        // [ebp-0x18]
		x::BuildBoneMatricesFromPose(hdr);
		x::ComputeBonesWorldMatrices(hdr, root);
		uint8_t *sk = PTR(PTR(ent, 0x64), 0);                             // [ebp-0x14]
		int32_t i = 1;                                                    // [ebp-0x10]
		int32_t maxx = S32(sk, 0x34);                                     // edi
		int32_t minx = maxx - 0x1F4;                                      // [ebp-8]
		maxx += 0x1F4;
		int32_t zz = S32(sk, 0x3C);
		int32_t minz = zz - 0x1F4;                                        // [ebp-0xc]
		int32_t maxz = zz + 0x1F4;                                        // [ebp+0xc]
		U32(w, 0xD0) = 0;
		if (U8(sk, 0) > 1)
		{
			uint8_t *m = sk + 0x50;                                       // [ebp-4]
			do
			{
				x::SetRotMatrix(m);
				x::SetTransVector(m);
				U16(w, 0xD4) = U16(m, -0xE);
				xl_RotTransIR(w + 0xD0, w + 0xD8, w + 0xFC);
				int32_t v = S16(w, 0xD8);
				if (v < minx) minx = v;
				else if (v > maxx) maxx = v;
				v = S16(w, 0xDC);
				if (v < minz) minz = v;
				else if (v > maxz) maxz = v;
				m += 0x30;
				i++;
			} while (i < (int32_t)U8(sk, 0));
		}
		int32_t hx = add32(minx, maxx) / 2;
		U16(w, 0xD0) = (uint16_t)(U16(pos, 0) + (uint16_t)hx);
		maxx = sub32(maxx, hx);                                           // edi = x half extent
		uint16_t pz = U16(pos, 4);
		U16(w, 0xD2) = 0;
		int32_t hz = add32(minz, maxz) / 2;
		maxz = sub32(maxz, hz);                                           // [ebp+0xc] = z half extent
		U16(w, 0xD4) = (uint16_t)(pz + (uint16_t)hz);
		x::SetRotMatrix(NODEMAT());
		x::SetTransVector(NODEMAT());
		uint8_t *flag = w + 0xFC;                                         // [ebp-0x10]
		xl_RotTransIR(w + 0xD0, w + 0xD8, flag);
		int32_t tx = S16(w, 0xD8);
		int32_t ty = S16(w, 0xDA);
		int32_t tz = S16(w, 0xDC);
		x::GteWriteCtrl(tx, 5);
		x::GteWriteCtrl(ty, 6);
		x::GteWriteCtrl(tz, 7);
		uint8_t *q = w + 0xB0;                                            // esi = 9 x 8-byte vertices
		int32_t cs = x::Cos(0x200);
		int32_t dz = maxz;                                                // edx
		int32_t dx = maxx;                                                // edi
		int32_t a = mul32(cs, dz) >> 12;                                  // eax
		int32_t c = mul32(cs, dx) >> 12;                                  // ecx
		U16(q, 0x04) = (uint16_t)dz;
		U16(q, 0x0C) = (uint16_t)a;
		U16(q, 0x08) = (uint16_t)c;
		U16(q, 0x18) = (uint16_t)c;
		int32_t na = -a, ndz = -dz, nc = -c;
		U16(q, 0x00) = 0;
		U16(q, 0x02) = 0;
		U16(q, 0x0A) = 0;
		U16(q, 0x10) = (uint16_t)dx;
		U16(q, 0x12) = 0;
		U16(q, 0x14) = 0;
		U16(q, 0x1A) = 0;
		U16(q, 0x1C) = (uint16_t)na;
		U16(q, 0x20) = 0;
		U16(q, 0x22) = 0;
		U16(q, 0x24) = (uint16_t)ndz;
		U16(q, 0x28) = (uint16_t)nc;
		int32_t ndx = -dx;
		U16(q, 0x38) = (uint16_t)nc;
		U16(q, 0x30) = (uint16_t)ndx;
		U16(q, 0x2A) = 0;
		U16(q, 0x2C) = (uint16_t)na;
		U16(q, 0x32) = 0;
		U16(q, 0x34) = 0;
		U16(q, 0x3A) = 0;
		U16(q, 0x3C) = (uint16_t)a;
		U16(q, 0x40) = 0;
		U16(q, 0x42) = 0;
		U16(q, 0x44) = 0;
		uint8_t *v = q;                                                   // edi
		for (int32_t n = 9; n != 0; n--)
		{
			xl_RotTransPers(v, v, flag, flag);
			v += 8;
		}
		if (xl_NormalClip(S32(q, 0), S32(q, 0x10), S32(q, 0x20)) > 0)
		{
			uint32_t ot = FRAMERL() + 0x4064;                             // [ebp+0x10]
			uint8_t *pkt = PTR(CTX(), 0x7C);                              // edi
			uint32_t code = U32(ent, 0x2C);                               // [ebp+0xc]
			int32_t k = 8;                                                // [ebp+8]
			do
			{
				U8(pkt, 3) = 8;
				U32(pkt, 8) = 0;
				U32(pkt, 4) = 0xE1000040;
				U32(pkt, 0xC) = code;
				U32(pkt, 0x14) = 0;
				U32(pkt, 0x1C) = 0;
				U32(pkt, 0x10) = U32(q, 0x40);
				U32(pkt, 0x18) = U32(q, k - 8);
				U32(pkt, 0x20) = U32(q, k & 0x38);
				x::InsertPrimDepthKeys(ot, pkt, 0, 0, 0, 0);
				k += 8;
				pkt += 0x24;
			} while (k - 8 < 0x40);
			PTR(CTX(), 0x7C) = pkt;
		}
		x::BuildBoneMatricesFromPose(hdr);
	}

	// ------------------------------------------------------------------------------------
	// 0xAF59D0 (Draw 38 AttachBattleEntity): entity = *(SceneHeader + 0x60 + 4*bone[0x1B]).
	// First call (bone+0xC4 == 0): bone+0xC4 = -1, entity[1] |= 0x10, bone+0xBC.. (3 x s16) =
	// Rzyx(-scene angles) * (entity+0x54.. - entity position). Every call: rotation =
	// Rzyx(scene angles (SceneHeader+0xD8+8*slot)), translation = rot * offset; pivot = joint
	// 0xF1 of the entity (blob 0xB66B80) before and after the entity rotation becomes
	// bone outAngle + scene angles (written to entity+0xC/+0xE/+0x10); entity position
	// (+0x1C/+0x1E/+0x20) = bone outPos + scene base position (SceneHeader+0x84+8*slot) - pivot
	// shift; then the entity shadow (0xAF5D00, root ws+0x60, pos ws+0x50).
	// Held frames: runs as vanilla with the in-between node pose (shadow at the in-between
	// transform), the entity bytes 0..0x23 (flags +0/+1, rotation, position) and the entity
	// skeleton are SAVED before and RESTORED after, so the entity keeps exactly the real tick's
	// state (bone+0xBC/+0xC4 are in the bone array, restored by HeldFrame).
	// ------------------------------------------------------------------------------------
	static void __cdecl dh_38_AttachBattleEntity()
	{
		uint8_t *bone = CUR();                                            // eax
		uint8_t *ent = PTR(SCENE(), 0x60 + 4 * (int32_t)U8(bone, 0x1B));  // esi
		EntityHeldSave hs;
		if (g_held.active) held_save_entity(hs, ent, 0x24);
		if (U32(bone, 0xC4) == 0)
		{
			U32(bone, 0xC4) = 0xFFFFFFFF;
			uint16_t d = U16(ent, 0x54);
			U8(ent, 1) |= 0x10;
			d = (uint16_t)(d - U16(ent, 0x1C));
			U16(WS(), 0xC0) = d;
			U16(WS(), 0xC2) = (uint16_t)(U16(ent, 0x58) - U16(ent, 0x1E));
			U16(WS(), 0xC4) = (uint16_t)(U16(ent, 0x5C) - U16(ent, 0x20));
			uint8_t *ang = SCENE() + 0xD8 + 8 * (int32_t)U8(CUR(), 0x1B);
			U16(WS(), 0xD0) = (uint16_t)(0 - U16(ang, 0));
			U16(WS(), 0xD2) = (uint16_t)(0 - U16(ang, 2));
			U16(WS(), 0xD4) = (uint16_t)(0 - U16(ang, 4));
			xl_ComposeZYXRotation(WS() + 0xD0, WS() + 0x60);
			x::SetRotMatrix(WS() + 0x60);
			x::SetTransVector(ZEROVEC());
			xl_RotTransIR(WS() + 0xC0, CUR() + 0xBC, WS() + 0xFC);
			bone = CUR();
		}
		uint8_t *off = bone + 0xBC;                                       // [ebp-4]
		uint8_t *ang = SCENE() + 0xD8 + 8 * (int32_t)U8(bone, 0x1B);      // edi
		xl_ComposeZYXRotation(ang, WS() + 0x60);
		xl_Apply3DTransform(WS() + 0x60, off, WS() + 0x74);
		uint8_t *hdr = ent + 0x60;                                        // ebx
		x::BuildBoneMatricesFromPose(hdr);
		blob::Blob_B66B80(hdr, 0xF1, 0x1000, WS() + 0x60);
		// ws+0xE2 = pad of the result: uninitialised temporary of ComposeAffineTransform 0x56C2F0
		GFC_TAINT(WS() + 0xE2, nullptr, 2);
		uint8_t *w = WS();
		int32_t oF0 = S32(w, 0xF0);                                       // [ebp-0x10]
		int32_t oF4 = S32(w, 0xF4);                                       // [ebp-8]
		int32_t oF8 = S32(w, 0xF8);                                       // [ebp-0xc]
		U16(w, 0xD0) = (uint16_t)(U16(CUR(), 0x8C) + U16(ang, 0));
		U16(ent, 0x0C) = U16(WS(), 0xD0);
		U16(WS(), 0xD2) = (uint16_t)(U16(CUR(), 0x8E) + U16(ang, 2));
		U16(ent, 0x0E) = U16(WS(), 0xD2);
		U16(WS(), 0xD4) = (uint16_t)(U16(CUR(), 0x90) + U16(ang, 4));
		U16(ent, 0x10) = U16(WS(), 0xD4);
		xl_ComposeZYXRotation(WS() + 0xD0, WS() + 0x60);
		xl_Apply3DTransform(WS() + 0x60, off, WS() + 0x74);
		blob::Blob_B66B80(hdr, 0xF1, 0x1000, WS() + 0x60);
		GFC_TAINT(WS() + 0xE2, nullptr, 2);
		w = WS();
		int32_t dz = sub32(S32(w, 0xF8), oF8);                            // edi
		int32_t dy = sub32(S32(w, 0xF4), oF4);                            // edx
		uint8_t *base = SCENE() + 0x84 + 8 * (int32_t)U8(CUR(), 0x1B);    // [ebp-4]
		uint8_t *p = w + 0x50;                                            // ecx
		uint16_t bx = (uint16_t)(U16(CUR(), 0x94) - (uint16_t)S32(w, 0xF0));
		bx = (uint16_t)(bx + U16(base, 0));
		uint16_t ax = (uint16_t)((uint16_t)oF0 + bx);
		U16(p, 0) = ax;
		U16(ent, 0x1C) = ax;
		ax = (uint16_t)(U16(CUR(), 0x96) + U16(base, 2));
		ax = (uint16_t)(ax - (uint16_t)dy);
		U16(p, 2) = ax;
		U16(ent, 0x1E) = ax;
		ax = (uint16_t)(U16(CUR(), 0x98) + U16(base, 4));
		ax = (uint16_t)(ax - (uint16_t)dz);
		U16(p, 4) = ax;
		U16(ent, 0x20) = ax;
		EntityShadow_AF5D00(ent, WS() + 0x60, p);
		if (g_held.active) held_restore_entity(hs);
	}

	// ------------------------------------------------------------------------------------
	// 0xAF6310 SyncEntityModelCopy(blk): blk+0x10..0x1B = entity+0x60..0x6B (BattleAnimHeader:
	// +0x14 = the entity's model pointer P), blk+0x30..0x3F = the 16 bytes at P (entity =
	// blk+0xC).
	// ------------------------------------------------------------------------------------
	static void SyncEntityModelCopy_AF6310(uint8_t *blk)
	{
		uint8_t *src = PTR(blk, 0xC) + 0x60;                              // eax / esi
		uint8_t *d = blk + 0x10;                                          // edx
		uint8_t *d2 = blk + 0x30;                                         // ecx
		U32(d, 0) = U32(src, 0);
		U32(d, 4) = U32(src, 4);
		U32(d, 8) = U32(src, 8);
		uint8_t *m = PTR(src, 4);
		U32(d2, 0) = U32(m, 0);
		U32(d2, 4) = U32(m, 4);
		U32(d2, 8) = U32(m, 8);
		U32(d2, 0xC) = U32(m, 0xC);
	}

	// ------------------------------------------------------------------------------------
	// 0xAF62B0 CreateEntityModelCopy(ent): 0x80-byte block from the arena: +0xC = ent, sync
	// (0xAF6310), render descriptor at +0x40: +0x50 = -1, +0x54 = 0, +0x58 = 0xD00140 (320x208),
	// +0x5C = +0x78 = ent+0x28, +0x60 = ent+0x7C, +0x64 (u16) = 0, +0x68 = 0; +0 / +2 (u16) = 0,
	// +0x21 (u8) = 0. Returns the block.
	// ------------------------------------------------------------------------------------
	static uint8_t *CreateEntityModelCopy_AF62B0(uint8_t *ent)
	{
		uint8_t *blk = blob::ArenaAlloc(0x80);                            // esi
		PTR(blk, 0xC) = ent;
		SyncEntityModelCopy_AF6310(blk);
		U32(blk, 0x54) = 0;
		U32(blk, 0x58) = 0xD00140;
		uint32_t t = U32(ent, 0x28);
		U32(blk, 0x78) = t;
		U32(blk, 0x5C) = t;
		t = U32(ent, 0x7C);
		U16(blk, 0x64) = 0;
		U32(blk, 0x60) = t;
		U32(blk, 0x68) = 0;
		U32(blk, 0x50) = 0xFFFFFFFF;
		U16(blk, 0) = 0;
		U16(blk, 2) = 0;
		U8(blk, 0x21) = 0;
		return blk;
	}

	// ------------------------------------------------------------------------------------
	// 0xAF6040 (Draw 48 DrawBattleEntityCopy): entity = *(SceneHeader + 0x60 + 4*bone[0x1B]),
	// reference node R = GetBone(*(s16 *)bone+0xB8). First call (bone+0xBC == 0): entity[0] |= 4,
	// bone+0xC0.. = R outPos (dword +0x94, word +0x98), bone+0xA8.. = R outAngle X/Y (dword +0x8C)
	// and R+0x98 as third "angle" (vanilla reads outPos Z there, used consistently below), bone+0xBC
	// = model copy block (0xAF62B0). Every call: ws+0x80 = scene angles - snapshot + R angles ->
	// RotMatrixOrder(.., 1) -> ws+0xE0; translation ws+0xF4.. = Rot(R outAngle) * (scene base pos -
	// snapshot pos) + R outPos (GTE); ws+0xE0 = camera node * ws+0xE0; re-sync the copy, world
	// matrices of the entity skeleton from ws+0xE0, RenderGeometry (mode 4, arena scratch at
	// block+0x44), bone matrices rebuilt from the entity pose.
	// Held frames: runs as vanilla with the in-between node pose (the copy is drawn at the
	// in-between transform, in the entity's current real pose); entity byte 0 and the entity
	// skeleton are saved before and restored after (arena + bone array: HeldFrame).
	// ------------------------------------------------------------------------------------
	static void __cdecl dh_48_DrawBattleEntityCopy()
	{
		uint8_t *bone = CUR();                                            // eax
		uint8_t *ent = PTR(SCENE(), 0x60 + 4 * (int32_t)U8(bone, 0x1B));  // esi
		EntityHeldSave hs;
		if (g_held.active) held_save_entity(hs, ent, 1);
		if (U32(bone, 0xBC) == 0)
		{
			U8(ent, 0) |= 4;
			uint8_t *r = blob::GetBone(S16(PTR(CUR(), 0xB8), 0));
			uint8_t *c = CUR() + 0xC0;
			U32(c, 0) = U32(r, 0x94);
			U16(c, 4) = U16(r, 0x98);
			c = CUR() + 0xA8;
			U32(c, 0) = U32(r, 0x8C);
			U16(c, 4) = U16(r, 0x98);
			uint8_t *blk = CreateEntityModelCopy_AF62B0(ent);
			PTR(CUR(), 0xBC) = blk;
		}
		uint8_t *r = blob::GetBone(S16(PTR(CUR(), 0xB8), 0));             // esi
		uint8_t *snap = CUR() + 0xA8;                                     // edx
		uint8_t *a = WS() + 0x80;                                         // eax
		uint8_t *ang = SCENE() + 0xD8 + 8 * (int32_t)U8(CUR(), 0x1B);     // ecx
		U16(a, 0) = (uint16_t)(U16(ang, 0) - U16(snap, 0) + U16(r, 0x8C));
		U16(a, 2) = (uint16_t)(U16(r, 0x8E) - U16(snap, 2) + U16(ang, 2));
		U16(a, 4) = (uint16_t)(U16(r, 0x98) - U16(snap, 4) + U16(ang, 4));
		blob::RotMatrixOrder(a, 1);                                       // -> ws+0xE0
		uint8_t *sp = CUR() + 0xC0;                                       // ebx
		uint8_t *base = SCENE() + 0x84 + 8 * (int32_t)U8(CUR(), 0x1B);    // edi
		x::RotMatrixFromAngles(r + 0x8C, WS() + 0xA0);
		int32_t tx = S16(r, 0x94);
		int32_t ty = S16(r, 0x96);
		int32_t tz = S16(r, 0x98);
		x::GteWriteCtrl(tx, 5);
		x::GteWriteCtrl(ty, 6);
		x::GteWriteCtrl(tz, 7);
		x::SetRotMatrix(WS() + 0xA0);
		U16(WS(), 0xC0) = (uint16_t)(U16(base, 0) - U16(sp, 0));
		U16(WS(), 0xC2) = (uint16_t)(U16(base, 2) - U16(sp, 2));
		U16(WS(), 0xC4) = (uint16_t)(U16(base, 4) - U16(sp, 4));
		uint8_t *w = WS();
		x::TransformToCamera(w + 0xC0, w + 0xF4, w + 0x9C);
		w = WS();
		x::ComposeAffine(NODEMAT(), w + 0xE0, w + 0xE0);
		// ws+0xF2 = pad of the product: uninitialised temporary of Matrix3x3_MultiplyPSX 0x56C090
		GFC_TAINT(w + 0xF2, nullptr, 2);
		uint8_t *blk = PTR(CUR(), 0xBC);                                  // esi
		uint8_t *hdr = blk + 0x10;                                        // edi
		uint8_t *desc = blk + 0x40;                                       // ebx
		SyncEntityModelCopy_AF6310(blk);
		x::ComputeBonesWorldMatrices(hdr, WS() + 0xE0);
		uint32_t ot = U32(RT(), 0x4C);
		uint32_t cursor = U32(CTX(), 0x7C);
		U32(desc, 4) = U32(CTX(), 0x74);
		U32(CTX(), 0x7C) = x::RenderGeometry(blk + 0x30, desc, ot, 4, cursor);
		x::BuildBoneMatricesFromPose(hdr);
		if (g_held.active) held_restore_entity(hs);
	}

	// ------------------------------------------------------------------------------------
	// 0xAFEFF0 (VM 0x09D RecenterModelOffsetBone): object w0 (blob ObjectPtr): vertices at
	// obj + *(obj+0x14), count *(obj+0x18), 8-byte stride. Bounding-box centre c (per axis
	// min + (max - min)/2, start min 0x7FFF / max -0x8000); cur accumPos (+0x5C/+0x60/+0x64) +=
	// ((c * w1..w3) / 256) << 16; the current bone handler; then every vertex -= c (16-bit, IN
	// PLACE in the file data: guard()ed while predicting). Length 10.
	// ------------------------------------------------------------------------------------
	static void __cdecl op_09D_RecenterModelOffsetBone()
	{
		uint8_t *obj = blob::ObjectPtr(S16(STREAM(), 2));                 // esi
		int32_t minz = 0x7FFF;                                            // [ebp-4] / ecx
		uint8_t *v = obj + U32(obj, 0x14);                                // edx
		int32_t n = S32(obj, 0x18);
		int32_t miny = 0x7FFF;                                            // ebx
		int32_t minx = 0x7FFF;                                            // edi
		int32_t maxz = -0x8000;                                           // [ebp-0x10]
		int32_t maxy = -0x8000;                                           // [ebp-0xc]
		int32_t maxx = -0x8000;                                           // [ebp-8]
		if (n > 0)
		{
			for (int32_t k = n; k != 0; k--)
			{
				int32_t t = S16(v, 0);
				if (t < minx) minx = t;
				if (t > maxx) maxx = t;
				t = S16(v, 2);
				if (t < miny) miny = t;
				if (t > maxy) maxy = t;
				t = S16(v, 4);
				if (t < minz) minz = t;
				if (t > maxz) maxz = t;
				v += 8;
			}
		}
		int32_t cz = minz;                                                // ecx
		minx = add32(minx, sub32(maxx, minx) / 2);                        // centre x (edi)
		int32_t p = mul32(S16(STREAM(), 4), minx);
		S32(CUR(), 0x5C) = add32(S32(CUR(), 0x5C), shl32(p / 256, 16));
		miny = add32(miny, sub32(maxy, miny) / 2);                        // centre y (ebx)
		p = mul32(S16(STREAM(), 6), miny);
		S32(CUR(), 0x60) = add32(S32(CUR(), 0x60), shl32(p / 256, 16));
		cz = add32(cz, sub32(maxz, cz) / 2);                              // centre z ([ebp-4])
		p = mul32(S16(STREAM(), 8), cz);
		{
			uint8_t *b = CUR();
			S32(b, 0x64) = add32(S32(b, 0x64), shl32(p / 256, 16));
		}
		(&C().bone[0])[U8(CUR(), 0x18)]();
		v = obj + U32(obj, 0x14);
		n = S32(obj, 0x18);
		if (n > 0)
		{
			guard(v, mul32(n, 8));
			for (; n != 0; n--)
			{
				U16(v, 0) = (uint16_t)(U16(v, 0) - (uint16_t)minx);
				U16(v, 2) = (uint16_t)(U16(v, 2) - (uint16_t)miny);
				U16(v, 4) = (uint16_t)(U16(v, 4) - (uint16_t)cz);
				v += 8;
			}
		}
		STREAM() += 0xA;
	}

	// ------------------------------------------------------------------------------------
	// 0xAFB240 (VM 0x0C5 JumpIfBattleStage): (u16 COMBAT_SCENE_ID, zero-extended) == (s16 w0,
	// sign-extended) -> STREAM += s16 w1, else STREAM += 6.
	// ------------------------------------------------------------------------------------
	static void __cdecl op_0C5_JumpIfBattleStage()
	{
		uint8_t *s = STREAM();
		int32_t stage = (int32_t)(MEM<uint32_t>(COMBAT_SCENE_ID_1CFF6E0) & 0xFFFF);
		if (stage == (int32_t)S16(s, 2))
			STREAM() = s + S16(s, 4);
		else
			STREAM() = s + 6;
	}

	// ------------------------------------------------------------------------------------
	// 0xAFB270 (VM 0x0D1 JumpIfModelSlot0FileId): (u16)(u8 battle model slot 0 file id) == u16 w0
	// -> STREAM += s16 w1, else STREAM += 6.
	// ------------------------------------------------------------------------------------
	static void __cdecl op_0D1_JumpIfModelSlot0FileId()
	{
		uint16_t id = MEM<uint8_t>(MODEL_SLOT0_FILEID_1D98990);
		uint8_t *s = STREAM();
		if (id == U16(s, 2))
			STREAM() = s + S16(s, 4);
		else
			STREAM() = s + 6;
	}

	// ------------------------------------------------------------------------------------
	// 0xAFB630 (VM 0x0D5 NorgBossTargetFixup): stage != 0x3F -> STREAM += 4. Stage 0x3F, sub-op
	// (op >> 12): 0 -> SceneHeader+0x48 == 3: flag 0x2796D40 = 0; else flag = 1, SceneHeader
	// +0x41 = 4, +0x4B = 3, +0x9C.. = 3 x u16 at 0x1D974B0, +0x54 = u16 at 0x1D97494, +0x6C =
	// 0x1D97494; STREAM += 4. 1 -> flag && bone[0x1B] == 3: STREAM += s16 w0, else += 4. Other
	// sub-ops: return WITHOUT advancing the cursor (vanilla). The flag byte is outside the engine
	// snapshot block: guard()ed.
	// ------------------------------------------------------------------------------------
	static void __cdecl op_0D5_NorgBossTargetFixup()
	{
		uint8_t &flag = MEM<uint8_t>(BROTHERS_FLAG_2796D40);
		if (MEM<uint16_t>(COMBAT_SCENE_ID_1CFF6E0) != 0x3F)
		{
			STREAM() += 4;
			return;
		}
		uint32_t sub = (uint32_t)U16(RT(), 0x4A) >> 12;
		if (sub == 0)
		{
			uint8_t *sc = SCENE();
			if (U8(sc, 0x48) == 3)
			{
				guard(&flag, 1);
				flag = 0;
				STREAM() += 4;
				return;
			}
			guard(&flag, 1);
			flag = 1;
			U8(sc, 0x41) = 4;
			U8(SCENE(), 0x4B) = 3;
			uint8_t *p = SCENE() + 0x9C;
			U16(p, 0) = MEM<uint16_t>(WORD_1D974B0);
			U16(p, 2) = MEM<uint16_t>(WORD_1D974B0 + 2);
			U16(p, 4) = MEM<uint16_t>(WORD_1D974B0 + 4);
			U16(SCENE(), 0x54) = MEM<uint16_t>(WORD_1D97494);
			U32(SCENE(), 0x6C) = WORD_1D97494;
			STREAM() += 4;
			return;
		}
		if (sub == 1)
		{
			if (flag != 0 && U8(CUR(), 0x1B) == 3)
			{
				uint8_t *s = STREAM();
				STREAM() = s + S16(s, 2);
			}
			else
				STREAM() += 4;
		}
	}

	// ------------------------------------------------------------------------------------
	// 0xAFDB00 (VM 0x0DA RenderEntityToVram). op bit 12 (rt+0x4B & 0x10): bone colour (+0xCC) =
	// (colour & 0x2000000) | 0x808000 | ((2*byte(0x1D98A4C) - 160) / 3 + 127); length 2.
	// Else, when the RenderCtx word +0x30 == 0: ws+0xD0..D6 = rect w0..w3; at the arena top d:
	// d+0 = d+4 = 0, d+0 = top+0xEC, d+8 = top+0x10EC, d+0xC = bone+0xC4 = 0x5BEC; ArenaAlloc(
	// 0x5BEC); d+0x14 = new top; off-screen render 0xB65F30(d, bone outPos, bone outAngle). Length
	// 10. Predicting: the 16 bytes written at the arena top before the allocation are guard()ed
	// (ArenaAlloc journals the rest), the render is skipped.
	// ------------------------------------------------------------------------------------
	static void __cdecl op_0DA_RenderEntityToVram()
	{
		if (U8(RT(), 0x4B) & 0x10)
		{
			uint32_t lv = MEM<uint32_t>(DWORD_1D98A4C) & 0xFF;
			uint8_t *b = CUR();                                           // ecx
			int32_t d = (int32_t)(lv + lv - 0xA0u);                       // lea edx, [eax+eax-0xa0]
			int32_t hi = (int32_t)(((int64_t)d * (int64_t)0x55555556) >> 32);
			uint32_t q = (uint32_t)hi + ((uint32_t)hi >> 31) + 0x7Fu;
			q |= U32(b, 0xCC) & 0x2000000;
			q |= 0x808000;
			U32(b, 0xCC) = q;
			STREAM() += 2;
			return;
		}
		if (U16(RCTX(), 0x30) == 0)
		{
			U16(WS(), 0xD0) = U16(STREAM(), 2);
			U16(WS(), 0xD2) = U16(STREAM(), 4);
			U16(WS(), 0xD4) = U16(STREAM(), 6);
			U16(WS(), 0xD6) = U16(STREAM(), 8);
			uint8_t *d = PTR(CTX(), 0x74);                                // esi
			guard(d, 0x10);
			U32(d, 0) = 0;
			U32(d, 4) = 0;
			U32(d, 0) = U32(CTX(), 0x74) + 0xEC;
			U32(d, 8) = U32(CTX(), 0x74) + 0x10EC;
			U32(d, 0xC) = 0x5BEC;
			U32(CUR(), 0xC4) = 0x5BEC;
			blob::ArenaAlloc(S32(d, 0xC));
			U32(d, 0x14) = U32(CTX(), 0x74);
			uint8_t *b = CUR();
			xl_OffscreenModelRender_B65F30(d, b + 0x94, b + 0x8C);
		}
		STREAM() += 0xA;
	}
}

	// installs the Brothers ports into a clone's tables (called after init_clone)
	void apply_brothers(Clone &c)
	{
		c.draw[3] = part_brothers::dh_03_AnimatedModelWithShadow;
		c.draw[38] = part_brothers::dh_38_AttachBattleEntity;
		c.draw[48] = part_brothers::dh_48_DrawBattleEntityCopy;
		c.vm[0x09D] = part_brothers::op_09D_RecenterModelOffsetBone;
		c.vm[0x0C5] = part_brothers::op_0C5_JumpIfBattleStage;
		c.vm[0x0D1] = part_brothers::op_0D1_JumpIfModelSlot0FileId;
		c.vm[0x0D5] = part_brothers::op_0D5_NorgBossTargetFixup;
		c.vm[0x0DA] = part_brothers::op_0DA_RenderEntityToVram;
	}
}
}
// ==== END clone handler parts ====




namespace ff8fx
{
namespace gfc
{
namespace brothers
{
	static Clone g_c = {};

	static void describe(Clone &c)
	{
		c.name = "205 Brothers";
		c.effect_id = 205;
		c.vm_table = 0x1871E4C;
		c.bone_table = 0x1871ABC;
		c.prim_table = 0x1871B04;
		c.prim_size = 0x1871BF4;
		c.spr_table = 0x1871C08;
		c.ptype_table = 0x1871C34;
		c.pop_table = 0x1871C48;
		c.draw_table = 0x1871CA8;
		c.attr_16A = 0x1871E12;
		c.attr_184 = 0x1871E2C;
		c.attr_186 = 0x1871E2E;
		c.attr_194 = 0x1871E3C;
		c.attr_19C = 0x1871E44;
		c.desc = 0x1871878;
		c.ptr_block = 0x1871A94;
		c.queue = 0x2796D30;
		c.file00 = 0x2796D6C;
		c.file01 = 0x2796D68;
		c.tick = 0xAF4B90;
		c.load_cb = 0xAFAD70;
		c.lit_dispatcher = false;
		c.bone_count = 18;
	}

	static uint32_t __cdecl SequenceTask(TaskNode *)
	{
		return SequenceTick(g_c);
	}

	static bool Ready() { return HeldReady(g_c); }
	static void Frame(int num, int den) { HeldFrame(g_c, num, den); }
	static bool Camera(int num, int den, int16_t world[3], int16_t lookat[3]) { return HeldCamera(g_c, num, den, world, lookat); }
}
}

	void register_gfc_brothers()
	{
		using namespace gfc;
		brothers::describe(brothers::g_c);
		init_clone(brothers::g_c, nullptr, 0);
		apply_brothers(brothers::g_c);
		apply_shared_misc(brothers::g_c);
		register_port(0xAF4B90, (void *)brothers::SequenceTask, "GFC205 Brothers SequenceTick", 205, true);
		register_module_held(205, brothers::Ready, brothers::Frame);
		register_module_camera(205, brothers::Camera);
	}
}
